/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.tables.pojos;


import ch.fhnw.labeling_tool.jooq.enums.CheckedUtteranceLabel;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.validation.constraints.NotNull;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckedUtterance implements Serializable {

    private static final long serialVersionUID = -944215990;

    private final Long                  id;
    private final Long                  utteranceId;
    private final Long                  userId;
    private final CheckedUtteranceLabel label;
    private final Timestamp             time;

    public CheckedUtterance(CheckedUtterance value) {
        this.id = value.id;
        this.utteranceId = value.utteranceId;
        this.userId = value.userId;
        this.label = value.label;
        this.time = value.time;
    }

    public CheckedUtterance(
        Long                  id,
        Long                  utteranceId,
        Long                  userId,
        CheckedUtteranceLabel label,
        Timestamp             time
    ) {
        this.id = id;
        this.utteranceId = utteranceId;
        this.userId = userId;
        this.label = label;
        this.time = time;
    }

    public Long getId() {
        return this.id;
    }

    @NotNull
    public Long getUtteranceId() {
        return this.utteranceId;
    }

    @NotNull
    public Long getUserId() {
        return this.userId;
    }

    public CheckedUtteranceLabel getLabel() {
        return this.label;
    }

    public Timestamp getTime() {
        return this.time;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CheckedUtterance (");

        sb.append(id);
        sb.append(", ").append(utteranceId);
        sb.append(", ").append(userId);
        sb.append(", ").append(label);
        sb.append(", ").append(time);

        sb.append(")");
        return sb.toString();
    }
}
