/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.tables.pojos;


import java.io.Serializable;

import javax.validation.constraints.Size;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Language implements Serializable {

    private static final long serialVersionUID = 1815112077;

    private Long   id;
    private String languageId;
    private String languageName;

    public Language() {}

    public Language(Language value) {
        this.id = value.id;
        this.languageId = value.languageId;
        this.languageName = value.languageName;
    }

    public Language(
        Long   id,
        String languageId,
        String languageName
    ) {
        this.id = id;
        this.languageId = languageId;
        this.languageName = languageName;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 100)
    public String getLanguageId() {
        return this.languageId;
    }

    public void setLanguageId(String languageId) {
        this.languageId = languageId;
    }

    @Size(max = 255)
    public String getLanguageName() {
        return this.languageName;
    }

    public void setLanguageName(String languageName) {
        this.languageName = languageName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Language (");

        sb.append(id);
        sb.append(", ").append(languageId);
        sb.append(", ").append(languageName);

        sb.append(")");
        return sb.toString();
    }
}
