/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.validation.constraints.NotNull;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OriginalText implements Serializable {

    private static final long serialVersionUID = -715219448;

    private Long      id;
    private Long      userGroupId;
    private Long      domainId;
    private Long      userId;
    private Timestamp time;

    public OriginalText() {}

    public OriginalText(OriginalText value) {
        this.id = value.id;
        this.userGroupId = value.userGroupId;
        this.domainId = value.domainId;
        this.userId = value.userId;
        this.time = value.time;
    }

    public OriginalText(
        Long      id,
        Long      userGroupId,
        Long      domainId,
        Long      userId,
        Timestamp time
    ) {
        this.id = id;
        this.userGroupId = userGroupId;
        this.domainId = domainId;
        this.userId = userId;
        this.time = time;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public Long getUserGroupId() {
        return this.userGroupId;
    }

    public void setUserGroupId(Long userGroupId) {
        this.userGroupId = userGroupId;
    }

    @NotNull
    public Long getDomainId() {
        return this.domainId;
    }

    public void setDomainId(Long domainId) {
        this.domainId = domainId;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Timestamp getTime() {
        return this.time;
    }

    public void setTime(Timestamp time) {
        this.time = time;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OriginalText (");

        sb.append(id);
        sb.append(", ").append(userGroupId);
        sb.append(", ").append(domainId);
        sb.append(", ").append(userId);
        sb.append(", ").append(time);

        sb.append(")");
        return sb.toString();
    }
}
