/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Recording implements Serializable {

    private static final long serialVersionUID = 473325205;

    private final Long      id;
    private final Long      excerptId;
    private final Long      userId;
    private final byte[]    audio;
    private final Timestamp time;

    public Recording(Recording value) {
        this.id = value.id;
        this.excerptId = value.excerptId;
        this.userId = value.userId;
        this.audio = value.audio;
        this.time = value.time;
    }

    public Recording(
        Long      id,
        Long      excerptId,
        Long      userId,
        byte[]    audio,
        Timestamp time
    ) {
        this.id = id;
        this.excerptId = excerptId;
        this.userId = userId;
        this.audio = audio;
        this.time = time;
    }

    public Long getId() {
        return this.id;
    }

    @NotNull
    public Long getExcerptId() {
        return this.excerptId;
    }

    @NotNull
    public Long getUserId() {
        return this.userId;
    }

    @Size(max = 16777215)
    public byte[] getAudio() {
        return this.audio;
    }

    public Timestamp getTime() {
        return this.time;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Recording (");

        sb.append(id);
        sb.append(", ").append(excerptId);
        sb.append(", ").append(userId);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(time);

        sb.append(")");
        return sb.toString();
    }
}
