/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.tables.pojos;


import ch.fhnw.labeling_tool.jooq.enums.SpeakerSex;

import java.io.Serializable;

import javax.validation.constraints.Size;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Speaker implements Serializable {

    private static final long serialVersionUID = -1090121822;

    private Long       id;
    private String     name;
    private String     language;
    private String     dialect;
    private SpeakerSex sex;

    public Speaker() {}

    public Speaker(Speaker value) {
        this.id = value.id;
        this.name = value.name;
        this.language = value.language;
        this.dialect = value.dialect;
        this.sex = value.sex;
    }

    public Speaker(
        Long       id,
        String     name,
        String     language,
        String     dialect,
        SpeakerSex sex
    ) {
        this.id = id;
        this.name = name;
        this.language = language;
        this.dialect = dialect;
        this.sex = sex;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Size(max = 45)
    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    @Size(max = 45)
    public String getDialect() {
        return this.dialect;
    }

    public void setDialect(String dialect) {
        this.dialect = dialect;
    }

    public SpeakerSex getSex() {
        return this.sex;
    }

    public void setSex(SpeakerSex sex) {
        this.sex = sex;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Speaker (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(language);
        sb.append(", ").append(dialect);
        sb.append(", ").append(sex);

        sb.append(")");
        return sb.toString();
    }
}
