/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.tables.pojos;


import java.io.Serializable;

import javax.validation.constraints.Size;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Speaker implements Serializable {

    private static final long serialVersionUID = -534141375;

    private Long   id;
    private String speakerId;
    private String languageUsed;
    private String dialect;

    public Speaker() {}

    public Speaker(Speaker value) {
        this.id = value.id;
        this.speakerId = value.speakerId;
        this.languageUsed = value.languageUsed;
        this.dialect = value.dialect;
    }

    public Speaker(
        Long   id,
        String speakerId,
        String languageUsed,
        String dialect
    ) {
        this.id = id;
        this.speakerId = speakerId;
        this.languageUsed = languageUsed;
        this.dialect = dialect;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 45)
    public String getSpeakerId() {
        return this.speakerId;
    }

    public void setSpeakerId(String speakerId) {
        this.speakerId = speakerId;
    }

    @Size(max = 45)
    public String getLanguageUsed() {
        return this.languageUsed;
    }

    public void setLanguageUsed(String languageUsed) {
        this.languageUsed = languageUsed;
    }

    @Size(max = 45)
    public String getDialect() {
        return this.dialect;
    }

    public void setDialect(String dialect) {
        this.dialect = dialect;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Speaker (");

        sb.append(id);
        sb.append(", ").append(speakerId);
        sb.append(", ").append(languageUsed);
        sb.append(", ").append(dialect);

        sb.append(")");
        return sb.toString();
    }
}
