/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.tables.pojos;


import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TextAudio implements Serializable {

    private static final long serialVersionUID = 958750013;

    private final Long    id;
    private final Double  audioStart;
    private final Double  audioEnd;
    private final String  text;
    private final Integer fileid;
    private final String  speaker;
    private final Integer labeled;
    private final Long    correct;
    private final Long    wrong;

    public TextAudio(TextAudio value) {
        this.id = value.id;
        this.audioStart = value.audioStart;
        this.audioEnd = value.audioEnd;
        this.text = value.text;
        this.fileid = value.fileid;
        this.speaker = value.speaker;
        this.labeled = value.labeled;
        this.correct = value.correct;
        this.wrong = value.wrong;
    }

    public TextAudio(
        Long    id,
        Double  audioStart,
        Double  audioEnd,
        String  text,
        Integer fileid,
        String  speaker,
        Integer labeled,
        Long    correct,
        Long    wrong
    ) {
        this.id = id;
        this.audioStart = audioStart;
        this.audioEnd = audioEnd;
        this.text = text;
        this.fileid = fileid;
        this.speaker = speaker;
        this.labeled = labeled;
        this.correct = correct;
        this.wrong = wrong;
    }

    public Long getId() {
        return this.id;
    }

    @NotNull
    public Double getAudioStart() {
        return this.audioStart;
    }

    @NotNull
    public Double getAudioEnd() {
        return this.audioEnd;
    }

    @Size(max = 16777215)
    public String getText() {
        return this.text;
    }

    @NotNull
    public Integer getFileid() {
        return this.fileid;
    }

    @Size(max = 45)
    public String getSpeaker() {
        return this.speaker;
    }

    public Integer getLabeled() {
        return this.labeled;
    }

    public Long getCorrect() {
        return this.correct;
    }

    public Long getWrong() {
        return this.wrong;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TextAudio (");

        sb.append(id);
        sb.append(", ").append(audioStart);
        sb.append(", ").append(audioEnd);
        sb.append(", ").append(text);
        sb.append(", ").append(fileid);
        sb.append(", ").append(speaker);
        sb.append(", ").append(labeled);
        sb.append(", ").append(correct);
        sb.append(", ").append(wrong);

        sb.append(")");
        return sb.toString();
    }
}
