/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.tables.pojos;


import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TextAudio implements Serializable {

    private static final long serialVersionUID = -534225959;

    private Long   id;
    private Double audioStart;
    private Double audioEnd;
    private String text;
    private String pathToFile;
    private Long   speakerId;
    private Long   sourceId;

    public TextAudio() {}

    public TextAudio(TextAudio value) {
        this.id = value.id;
        this.audioStart = value.audioStart;
        this.audioEnd = value.audioEnd;
        this.text = value.text;
        this.pathToFile = value.pathToFile;
        this.speakerId = value.speakerId;
        this.sourceId = value.sourceId;
    }

    public TextAudio(
        Long   id,
        Double audioStart,
        Double audioEnd,
        String text,
        String pathToFile,
        Long   speakerId,
        Long   sourceId
    ) {
        this.id = id;
        this.audioStart = audioStart;
        this.audioEnd = audioEnd;
        this.text = text;
        this.pathToFile = pathToFile;
        this.speakerId = speakerId;
        this.sourceId = sourceId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public Double getAudioStart() {
        return this.audioStart;
    }

    public void setAudioStart(Double audioStart) {
        this.audioStart = audioStart;
    }

    @NotNull
    public Double getAudioEnd() {
        return this.audioEnd;
    }

    public void setAudioEnd(Double audioEnd) {
        this.audioEnd = audioEnd;
    }

    @NotNull
    @Size(max = 16777215)
    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    @Size(max = 255)
    public String getPathToFile() {
        return this.pathToFile;
    }

    public void setPathToFile(String pathToFile) {
        this.pathToFile = pathToFile;
    }

    @NotNull
    public Long getSpeakerId() {
        return this.speakerId;
    }

    public void setSpeakerId(Long speakerId) {
        this.speakerId = speakerId;
    }

    @NotNull
    public Long getSourceId() {
        return this.sourceId;
    }

    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TextAudio (");

        sb.append(id);
        sb.append(", ").append(audioStart);
        sb.append(", ").append(audioEnd);
        sb.append(", ").append(text);
        sb.append(", ").append(pathToFile);
        sb.append(", ").append(speakerId);
        sb.append(", ").append(sourceId);

        sb.append(")");
        return sb.toString();
    }
}
