/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.tables.pojos;


import ch.fhnw.labeling_tool.jooq.enums.UserGroupRoleRole;

import java.io.Serializable;

import javax.validation.constraints.NotNull;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroupRole implements Serializable {

    private static final long serialVersionUID = 139027262;

    private Long              id;
    private UserGroupRoleRole role;
    private Long              userId;
    private Long              userGroupId;

    public UserGroupRole() {}

    public UserGroupRole(UserGroupRole value) {
        this.id = value.id;
        this.role = value.role;
        this.userId = value.userId;
        this.userGroupId = value.userGroupId;
    }

    public UserGroupRole(
        Long              id,
        UserGroupRoleRole role,
        Long              userId,
        Long              userGroupId
    ) {
        this.id = id;
        this.role = role;
        this.userId = userId;
        this.userGroupId = userGroupId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public UserGroupRoleRole getRole() {
        return this.role;
    }

    public void setRole(UserGroupRoleRole role) {
        this.role = role;
    }

    @NotNull
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @NotNull
    public Long getUserGroupId() {
        return this.userGroupId;
    }

    public void setUserGroupId(Long userGroupId) {
        this.userGroupId = userGroupId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserGroupRole (");

        sb.append(id);
        sb.append(", ").append(role);
        sb.append(", ").append(userId);
        sb.append(", ").append(userGroupId);

        sb.append(")");
        return sb.toString();
    }
}
