/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.tables.pojos;


import ch.fhnw.labeling_tool.jooq.enums.UserGroupRoleRole;

import java.io.Serializable;

import javax.validation.constraints.NotNull;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroupRole implements Serializable {

    private static final long serialVersionUID = -710998947;

    private final UserGroupRoleRole role;
    private final Long              userId;
    private final Long              userGroupId;

    public UserGroupRole(UserGroupRole value) {
        this.role = value.role;
        this.userId = value.userId;
        this.userGroupId = value.userGroupId;
    }

    public UserGroupRole(
        UserGroupRoleRole role,
        Long              userId,
        Long              userGroupId
    ) {
        this.role = role;
        this.userId = userId;
        this.userGroupId = userGroupId;
    }

    public UserGroupRoleRole getRole() {
        return this.role;
    }

    @NotNull
    public Long getUserId() {
        return this.userId;
    }

    @NotNull
    public Long getUserGroupId() {
        return this.userGroupId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserGroupRole (");

        sb.append(role);
        sb.append(", ").append(userId);
        sb.append(", ").append(userGroupId);

        sb.append(")");
        return sb.toString();
    }
}
