/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.tables.daos;


import ch.fhnw.labeling_tool.jooq.tables.Domain;
import ch.fhnw.labeling_tool.jooq.tables.records.DomainRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class DomainDao extends DAOImpl<DomainRecord, ch.fhnw.labeling_tool.jooq.tables.pojos.Domain, Long> {

    public DomainDao() {
        super(Domain.DOMAIN, ch.fhnw.labeling_tool.jooq.tables.pojos.Domain.class);
    }

    @Autowired
    public DomainDao(Configuration configuration) {
        super(Domain.DOMAIN, ch.fhnw.labeling_tool.jooq.tables.pojos.Domain.class, configuration);
    }

    @Override
    public Long getId(ch.fhnw.labeling_tool.jooq.tables.pojos.Domain object) {
        return object.getId();
    }

    public List<ch.fhnw.labeling_tool.jooq.tables.pojos.Domain> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Domain.DOMAIN.ID, lowerInclusive, upperInclusive);
    }

    public List<ch.fhnw.labeling_tool.jooq.tables.pojos.Domain> fetchById(Long... values) {
        return fetch(Domain.DOMAIN.ID, values);
    }

    public ch.fhnw.labeling_tool.jooq.tables.pojos.Domain fetchOneById(Long value) {
        return fetchOne(Domain.DOMAIN.ID, value);
    }

    public List<ch.fhnw.labeling_tool.jooq.tables.pojos.Domain> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Domain.DOMAIN.NAME, lowerInclusive, upperInclusive);
    }

    public List<ch.fhnw.labeling_tool.jooq.tables.pojos.Domain> fetchByName(String... values) {
        return fetch(Domain.DOMAIN.NAME, values);
    }
}
