/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.tables.daos;


import ch.fhnw.labeling_tool.jooq.tables.OriginalText;
import ch.fhnw.labeling_tool.jooq.tables.records.OriginalTextRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class OriginalTextDao extends DAOImpl<OriginalTextRecord, ch.fhnw.labeling_tool.jooq.tables.pojos.OriginalText, Long> {

    public OriginalTextDao() {
        super(OriginalText.ORIGINAL_TEXT, ch.fhnw.labeling_tool.jooq.tables.pojos.OriginalText.class);
    }

    @Autowired
    public OriginalTextDao(Configuration configuration) {
        super(OriginalText.ORIGINAL_TEXT, ch.fhnw.labeling_tool.jooq.tables.pojos.OriginalText.class, configuration);
    }

    @Override
    protected Long getId(ch.fhnw.labeling_tool.jooq.tables.pojos.OriginalText object) {
        return object.getId();
    }

    public List<ch.fhnw.labeling_tool.jooq.tables.pojos.OriginalText> fetchById(Long... values) {
        return fetch(OriginalText.ORIGINAL_TEXT.ID, values);
    }

    public ch.fhnw.labeling_tool.jooq.tables.pojos.OriginalText fetchOneById(Long value) {
        return fetchOne(OriginalText.ORIGINAL_TEXT.ID, value);
    }

    public List<ch.fhnw.labeling_tool.jooq.tables.pojos.OriginalText> fetchByUserGroupId(Long... values) {
        return fetch(OriginalText.ORIGINAL_TEXT.USER_GROUP_ID, values);
    }
}
