/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.tables.daos;


import ch.fhnw.labeling_tool.jooq.enums.UserLicence;
import ch.fhnw.labeling_tool.jooq.enums.UserSex;
import ch.fhnw.labeling_tool.jooq.tables.User;
import ch.fhnw.labeling_tool.jooq.tables.records.UserRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class UserDao extends DAOImpl<UserRecord, ch.fhnw.labeling_tool.jooq.tables.pojos.User, Long> {

    public UserDao() {
        super(User.USER, ch.fhnw.labeling_tool.jooq.tables.pojos.User.class);
    }

    @Autowired
    public UserDao(Configuration configuration) {
        super(User.USER, ch.fhnw.labeling_tool.jooq.tables.pojos.User.class, configuration);
    }

    @Override
    protected Long getId(ch.fhnw.labeling_tool.jooq.tables.pojos.User object) {
        return object.getId();
    }

    public List<ch.fhnw.labeling_tool.jooq.tables.pojos.User> fetchById(Long... values) {
        return fetch(User.USER.ID, values);
    }

    public ch.fhnw.labeling_tool.jooq.tables.pojos.User fetchOneById(Long value) {
        return fetchOne(User.USER.ID, value);
    }

    public List<ch.fhnw.labeling_tool.jooq.tables.pojos.User> fetchByFirstName(String... values) {
        return fetch(User.USER.FIRST_NAME, values);
    }

    public List<ch.fhnw.labeling_tool.jooq.tables.pojos.User> fetchByLastName(String... values) {
        return fetch(User.USER.LAST_NAME, values);
    }

    public List<ch.fhnw.labeling_tool.jooq.tables.pojos.User> fetchByEmail(String... values) {
        return fetch(User.USER.EMAIL, values);
    }

    public ch.fhnw.labeling_tool.jooq.tables.pojos.User fetchOneByEmail(String value) {
        return fetchOne(User.USER.EMAIL, value);
    }

    public List<ch.fhnw.labeling_tool.jooq.tables.pojos.User> fetchByUsername(String... values) {
        return fetch(User.USER.USERNAME, values);
    }

    public ch.fhnw.labeling_tool.jooq.tables.pojos.User fetchOneByUsername(String value) {
        return fetchOne(User.USER.USERNAME, value);
    }

    public List<ch.fhnw.labeling_tool.jooq.tables.pojos.User> fetchByPassword(String... values) {
        return fetch(User.USER.PASSWORD, values);
    }

    public List<ch.fhnw.labeling_tool.jooq.tables.pojos.User> fetchByCanton(String... values) {
        return fetch(User.USER.CANTON, values);
    }

    public List<ch.fhnw.labeling_tool.jooq.tables.pojos.User> fetchBySex(UserSex... values) {
        return fetch(User.USER.SEX, values);
    }

    public List<ch.fhnw.labeling_tool.jooq.tables.pojos.User> fetchByLicence(UserLicence... values) {
        return fetch(User.USER.LICENCE, values);
    }
}
