/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.tables.daos;


import ch.fhnw.labeling_tool.jooq.enums.UserGroupRoleRole;
import ch.fhnw.labeling_tool.jooq.tables.UserGroupRole;
import ch.fhnw.labeling_tool.jooq.tables.records.UserGroupRoleRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class UserGroupRoleDao extends DAOImpl<UserGroupRoleRecord, ch.fhnw.labeling_tool.jooq.tables.pojos.UserGroupRole, Long> {

    public UserGroupRoleDao() {
        super(UserGroupRole.USER_GROUP_ROLE, ch.fhnw.labeling_tool.jooq.tables.pojos.UserGroupRole.class);
    }

    @Autowired
    public UserGroupRoleDao(Configuration configuration) {
        super(UserGroupRole.USER_GROUP_ROLE, ch.fhnw.labeling_tool.jooq.tables.pojos.UserGroupRole.class, configuration);
    }

    @Override
    protected Long getId(ch.fhnw.labeling_tool.jooq.tables.pojos.UserGroupRole object) {
        return object.getId();
    }

    public List<ch.fhnw.labeling_tool.jooq.tables.pojos.UserGroupRole> fetchById(Long... values) {
        return fetch(UserGroupRole.USER_GROUP_ROLE.ID, values);
    }

    public ch.fhnw.labeling_tool.jooq.tables.pojos.UserGroupRole fetchOneById(Long value) {
        return fetchOne(UserGroupRole.USER_GROUP_ROLE.ID, value);
    }

    public List<ch.fhnw.labeling_tool.jooq.tables.pojos.UserGroupRole> fetchByRole(UserGroupRoleRole... values) {
        return fetch(UserGroupRole.USER_GROUP_ROLE.ROLE, values);
    }

    public List<ch.fhnw.labeling_tool.jooq.tables.pojos.UserGroupRole> fetchByUserId(Long... values) {
        return fetch(UserGroupRole.USER_GROUP_ROLE.USER_ID, values);
    }

    public List<ch.fhnw.labeling_tool.jooq.tables.pojos.UserGroupRole> fetchByUserGroupId(Long... values) {
        return fetch(UserGroupRole.USER_GROUP_ROLE.USER_GROUP_ID, values);
    }
}
