/*
 * This file is generated by jOOQ.
 */
package ch.labeling_tool.db.tables


import ch.labeling_tool.db.Indexes
import ch.labeling_tool.db.Keys
import ch.labeling_tool.db.LabelingTool
import ch.labeling_tool.db.tables.records.AudioRecord

import java.lang.Class
import java.lang.Integer
import java.lang.String
import java.util.Arrays
import java.util.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.TableImpl

import scala.Array


object Audio {

  val AUDIO = new Audio
}

class Audio(
  alias : Name,
  child : Table[_ <: Record],
  path : ForeignKey[_ <: Record, AudioRecord],
  aliased : Table[AudioRecord],
  parameters : Array[ Field[_] ]
)
extends TableImpl[AudioRecord](
  alias,
  LabelingTool.LABELING_TOOL,
  child,
  path,
  aliased,
  parameters,
  DSL.comment("")
)
{

  override def getRecordType : Class[AudioRecord] = {
    classOf[AudioRecord]
  }

  val ID : TableField[AudioRecord, Integer] = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), "")

  val PATH : TableField[AudioRecord, String] = createField("path", org.jooq.impl.SQLDataType.VARCHAR(200), "")

  val FILEID : TableField[AudioRecord, Integer] = createField("fileId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), "")

  def this() = {
    this(DSL.name("audio"), null, null, null, null)
  }

  def this(alias : String) = {
    this(DSL.name(alias), null, null, ch.labeling_tool.db.tables.Audio.AUDIO, null)
  }

  def this(alias : Name) = {
    this(alias, null, null, ch.labeling_tool.db.tables.Audio.AUDIO, null)
  }

  private def this(alias : Name, aliased : Table[AudioRecord]) = {
    this(alias, null, null, aliased, null)
  }

  def this(child : Table[_ <: Record], key : ForeignKey[_ <: Record, AudioRecord]) = {
    this(Internal.createPathAlias(child, key), child, key, ch.labeling_tool.db.tables.Audio.AUDIO, null)
  }

  override def getSchema : Schema = LabelingTool.LABELING_TOOL

  override def getIndexes : List[ Index ] = {
    return Arrays.asList[ Index ](Indexes.AUDIO_PRIMARY)
  }

  override def getIdentity : Identity[AudioRecord, Integer] = {
    Keys.IDENTITY_AUDIO
  }

  override def getPrimaryKey : UniqueKey[AudioRecord] = {
    Keys.KEY_AUDIO_PRIMARY
  }

  override def getKeys : List[ UniqueKey[AudioRecord] ] = {
    return Arrays.asList[ UniqueKey[AudioRecord] ](Keys.KEY_AUDIO_PRIMARY)
  }

  override def as(alias : String) : Audio = {
    new Audio(DSL.name(alias), this)
  }

  override def as(alias : Name) : Audio = {
    new Audio(alias, this)
  }

  override def rename(name : String) : Audio = {
    new Audio(DSL.name(name), null)
  }

  override def rename(name : Name) : Audio = {
    new Audio(name, null)
  }
}
