/*
 * This file is generated by jOOQ.
 */
package ch.labeling_tool.db.tables


import ch.labeling_tool.db.Indexes
import ch.labeling_tool.db.Keys
import ch.labeling_tool.db.LabelingTool
import ch.labeling_tool.db.tables.records.ChatmemberRecord

import java.lang.Class
import java.lang.Integer
import java.lang.String
import java.util.Arrays
import java.util.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.TableImpl

import scala.Array


object Chatmember {

  val CHATMEMBER = new Chatmember
}

class Chatmember(
  alias : Name,
  child : Table[_ <: Record],
  path : ForeignKey[_ <: Record, ChatmemberRecord],
  aliased : Table[ChatmemberRecord],
  parameters : Array[ Field[_] ]
)
extends TableImpl[ChatmemberRecord](
  alias,
  LabelingTool.LABELING_TOOL,
  child,
  path,
  aliased,
  parameters,
  DSL.comment("")
)
{

  override def getRecordType : Class[ChatmemberRecord] = {
    classOf[ChatmemberRecord]
  }

  val ID : TableField[ChatmemberRecord, Integer] = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), "")

  val CHATID : TableField[ChatmemberRecord, Integer] = createField("chatId", org.jooq.impl.SQLDataType.INTEGER, "")

  val USERID : TableField[ChatmemberRecord, Integer] = createField("userId", org.jooq.impl.SQLDataType.INTEGER, "")

  def this() = {
    this(DSL.name("chatMember"), null, null, null, null)
  }

  def this(alias : String) = {
    this(DSL.name(alias), null, null, ch.labeling_tool.db.tables.Chatmember.CHATMEMBER, null)
  }

  def this(alias : Name) = {
    this(alias, null, null, ch.labeling_tool.db.tables.Chatmember.CHATMEMBER, null)
  }

  private def this(alias : Name, aliased : Table[ChatmemberRecord]) = {
    this(alias, null, null, aliased, null)
  }

  def this(child : Table[_ <: Record], key : ForeignKey[_ <: Record, ChatmemberRecord]) = {
    this(Internal.createPathAlias(child, key), child, key, ch.labeling_tool.db.tables.Chatmember.CHATMEMBER, null)
  }

  override def getSchema : Schema = LabelingTool.LABELING_TOOL

  override def getIndexes : List[ Index ] = {
    return Arrays.asList[ Index ](Indexes.CHATMEMBER_PRIMARY, Indexes.CHATMEMBER_UNI)
  }

  override def getIdentity : Identity[ChatmemberRecord, Integer] = {
    Keys.IDENTITY_CHATMEMBER
  }

  override def getPrimaryKey : UniqueKey[ChatmemberRecord] = {
    Keys.KEY_CHATMEMBER_PRIMARY
  }

  override def getKeys : List[ UniqueKey[ChatmemberRecord] ] = {
    return Arrays.asList[ UniqueKey[ChatmemberRecord] ](Keys.KEY_CHATMEMBER_PRIMARY, Keys.KEY_CHATMEMBER_UNI)
  }

  override def as(alias : String) : Chatmember = {
    new Chatmember(DSL.name(alias), this)
  }

  override def as(alias : Name) : Chatmember = {
    new Chatmember(alias, this)
  }

  override def rename(name : String) : Chatmember = {
    new Chatmember(DSL.name(name), null)
  }

  override def rename(name : Name) : Chatmember = {
    new Chatmember(name, null)
  }
}
