/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum SourceLicence implements EnumType {

    PUBLIC("PUBLIC"),

    ACADEMIC("ACADEMIC");

    private final String literal;

    private SourceLicence(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "source_licence";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
