/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum UserGroupRoleRole implements EnumType {

    ADMIN("ADMIN"),

    GROUP_ADMIN("GROUP_ADMIN"),

    USER("USER");

    private final String literal;

    private UserGroupRoleRole(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "user_group_role_role";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
