/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum UserAge implements EnumType {

    NONE("NONE"),

    U20("U20"),

    U30("U30"),

    U40("U40"),

    U50("U50"),

    U60_27U70_27U70("U60'U70'U70"),

    O80("O80");

    private final String literal;

    private UserAge(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "user_age";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
