/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables.pojos


import java.io.Serializable
import java.lang.Integer
import java.lang.StringBuilder


case class Chatmember(
    id : Integer
  , chatid : Integer
  , userid : Integer
) extends Serializable {

  def this (value : Chatmember) = {
    this(
        value.id
      , value.chatid
      , value.userid
    )
  }

  def getId : Integer = {
    this.id
  }

  def getChatid : Integer = {
    this.chatid
  }

  def getUserid : Integer = {
    this.userid
  }

  override def toString : String = {
    val sb = new StringBuilder("Chatmember (")

    sb.append(id)
    sb.append(", ").append(chatid)
    sb.append(", ").append(userid)

    sb.append(")")
    return sb.toString
  }
}
