/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables.pojos


import java.io.Serializable
import java.lang.Double
import java.lang.Integer
import java.lang.StringBuilder


case class Match(
    matchid : Integer
  , audiostart : Double
  , audioend : Double
  , textstart : Double
  , textend : Double
) extends Serializable {

  def this (value : Match) = {
    this(
        value.matchid
      , value.audiostart
      , value.audioend
      , value.textstart
      , value.textend
    )
  }

  def getMatchid : Integer = {
    this.matchid
  }

  def getAudiostart : Double = {
    this.audiostart
  }

  def getAudioend : Double = {
    this.audioend
  }

  def getTextstart : Double = {
    this.textstart
  }

  def getTextend : Double = {
    this.textend
  }

  override def toString : String = {
    val sb = new StringBuilder("Match (")

    sb.append(matchid)
    sb.append(", ").append(audiostart)
    sb.append(", ").append(audioend)
    sb.append(", ").append(textstart)
    sb.append(", ").append(textend)

    sb.append(")")
    return sb.toString
  }
}
