/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables.pojos


import java.io.Serializable
import java.lang.Integer
import java.lang.String
import java.lang.StringBuilder

import scala.Array
import scala.Byte


case class Recordings(
    id : Integer
  , text : String
  , userid : Integer
  , audio : Array[Byte]
) extends Serializable {

  def this (value : Recordings) = {
    this(
        value.id
      , value.text
      , value.userid
      , value.audio
    )
  }

  def getId : Integer = {
    this.id
  }

  def getText : String = {
    this.text
  }

  def getUserid : Integer = {
    this.userid
  }

  def getAudio : Array[Byte] = {
    this.audio
  }

  override def toString : String = {
    val sb = new StringBuilder("Recordings (")

    sb.append(id)
    sb.append(", ").append(text)
    sb.append(", ").append(userid)
    sb.append(", ").append("[binary...]")

    sb.append(")")
    return sb.toString
  }
}
