/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables.pojos


import java.io.Serializable
import java.lang.Long
import java.lang.String
import java.lang.StringBuilder


case class Speaker(
    id : Long
  , speakerid : String
  , sex : String
  , languageused : String
  , dialect : String
) extends Serializable {

  def this (value : Speaker) = {
    this(
        value.id
      , value.speakerid
      , value.sex
      , value.languageused
      , value.dialect
    )
  }

  def getId : Long = {
    this.id
  }

  def getSpeakerid : String = {
    this.speakerid
  }

  def getSex : String = {
    this.sex
  }

  def getLanguageused : String = {
    this.languageused
  }

  def getDialect : String = {
    this.dialect
  }

  override def toString : String = {
    val sb = new StringBuilder("Speaker (")

    sb.append(id)
    sb.append(", ").append(speakerid)
    sb.append(", ").append(sex)
    sb.append(", ").append(languageused)
    sb.append(", ").append(dialect)

    sb.append(")")
    return sb.toString
  }
}
