/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables.pojos


import java.io.Serializable
import java.lang.Integer
import java.lang.StringBuilder


case class Textaudioindex(
    id : Integer
  , textstartpos : Integer
  , textendpos : Integer
  , audiostartpos : Integer
  , audioendpos : Integer
  , speakerkey : Integer
) extends Serializable {

  def this (value : Textaudioindex) = {
    this(
        value.id
      , value.textstartpos
      , value.textendpos
      , value.audiostartpos
      , value.audioendpos
      , value.speakerkey
    )
  }

  def getId : Integer = {
    this.id
  }

  def getTextstartpos : Integer = {
    this.textstartpos
  }

  def getTextendpos : Integer = {
    this.textendpos
  }

  def getAudiostartpos : Integer = {
    this.audiostartpos
  }

  def getAudioendpos : Integer = {
    this.audioendpos
  }

  def getSpeakerkey : Integer = {
    this.speakerkey
  }

  override def toString : String = {
    val sb = new StringBuilder("Textaudioindex (")

    sb.append(id)
    sb.append(", ").append(textstartpos)
    sb.append(", ").append(textendpos)
    sb.append(", ").append(audiostartpos)
    sb.append(", ").append(audioendpos)
    sb.append(", ").append(speakerkey)

    sb.append(")")
    return sb.toString
  }
}
