/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables.pojos


import java.io.Serializable
import java.lang.Integer
import java.lang.StringBuilder

import scala.Array
import scala.Byte


case class Transcript(
    id : Integer
  , file : Array[Byte]
) extends Serializable {

  def this (value : Transcript) = {
    this(
        value.id
      , value.file
    )
  }

  def getId : Integer = {
    this.id
  }

  def getFile : Array[Byte] = {
    this.file
  }

  override def toString : String = {
    val sb = new StringBuilder("Transcript (")

    sb.append(id)
    sb.append(", ").append("[binary...]")

    sb.append(")")
    return sb.toString
  }
}
