/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables.pojos


import java.io.Serializable
import java.lang.Long
import java.lang.String
import java.lang.StringBuilder


case class Userandtextaudio(
    id : Long
  , userid : Long
  , textaudioid : String
  , time : String
) extends Serializable {

  def this (value : Userandtextaudio) = {
    this(
        value.id
      , value.userid
      , value.textaudioid
      , value.time
    )
  }

  def getId : Long = {
    this.id
  }

  def getUserid : Long = {
    this.userid
  }

  def getTextaudioid : String = {
    this.textaudioid
  }

  def getTime : String = {
    this.time
  }

  override def toString : String = {
    val sb = new StringBuilder("Userandtextaudio (")

    sb.append(id)
    sb.append(", ").append(userid)
    sb.append(", ").append(textaudioid)
    sb.append(", ").append(time)

    sb.append(")")
    return sb.toString
  }
}
