/*
 * This file is generated by jOOQ.
 */
package ch.labeling_tool.db.tables.records


import ch.labeling_tool.db.tables.Chatmessage

import java.lang.Integer
import java.lang.String

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record3
import org.jooq.Row3
import org.jooq.impl.UpdatableRecordImpl


class ChatmessageRecord extends UpdatableRecordImpl[ChatmessageRecord](Chatmessage.CHATMESSAGE) with Record3[Integer, Integer, String] {

  def setId(value : Integer) : Unit = {
    set(0, value)
  }

  def getId : Integer = {
    val r = get(0)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  def setChatmemberid(value : Integer) : Unit = {
    set(1, value)
  }

  def getChatmemberid : Integer = {
    val r = get(1)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  def setMessage(value : String) : Unit = {
    set(2, value)
  }

  def getMessage : String = {
    val r = get(2)
    if (r == null) null else r.asInstanceOf[String]
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------
  override def key : Record1[Integer] = {
    return super.key.asInstanceOf[ Record1[Integer] ]
  }

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow : Row3[Integer, Integer, String] = {
    super.fieldsRow.asInstanceOf[ Row3[Integer, Integer, String] ]
  }

  override def valuesRow : Row3[Integer, Integer, String] = {
    super.valuesRow.asInstanceOf[ Row3[Integer, Integer, String] ]
  }
  override def field1 : Field[Integer] = Chatmessage.CHATMESSAGE.ID
  override def field2 : Field[Integer] = Chatmessage.CHATMESSAGE.CHATMEMBERID
  override def field3 : Field[String] = Chatmessage.CHATMESSAGE.MESSAGE
  override def component1 : Integer = getId
  override def component2 : Integer = getChatmemberid
  override def component3 : String = getMessage
  override def value1 : Integer = getId
  override def value2 : Integer = getChatmemberid
  override def value3 : String = getMessage

  override def value1(value : Integer) : ChatmessageRecord = {
    setId(value)
    this
  }

  override def value2(value : Integer) : ChatmessageRecord = {
    setChatmemberid(value)
    this
  }

  override def value3(value : String) : ChatmessageRecord = {
    setMessage(value)
    this
  }

  override def values(value1 : Integer, value2 : Integer, value3 : String) : ChatmessageRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this
  }

  def this(id : Integer, chatmemberid : Integer, message : String) = {
    this()

    set(0, id)
    set(1, chatmemberid)
    set(2, message)
  }
}
