/*
 * This file is generated by jOOQ.
 */
package ch.labeling_tool.db.tables.records


import ch.labeling_tool.db.tables.Userandtextaudioindex

import java.lang.Integer

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record3
import org.jooq.Row3
import org.jooq.impl.UpdatableRecordImpl


class UserandtextaudioindexRecord extends UpdatableRecordImpl[UserandtextaudioindexRecord](Userandtextaudioindex.USERANDTEXTAUDIOINDEX) with Record3[Integer, Integer, Integer] {

  def setId(value : Integer) : Unit = {
    set(0, value)
  }

  def getId : Integer = {
    val r = get(0)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  def setUserid(value : Integer) : Unit = {
    set(1, value)
  }

  def getUserid : Integer = {
    val r = get(1)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  def setTextaudioindexid(value : Integer) : Unit = {
    set(2, value)
  }

  def getTextaudioindexid : Integer = {
    val r = get(2)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------
  override def key : Record1[Integer] = {
    return super.key.asInstanceOf[ Record1[Integer] ]
  }

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow : Row3[Integer, Integer, Integer] = {
    super.fieldsRow.asInstanceOf[ Row3[Integer, Integer, Integer] ]
  }

  override def valuesRow : Row3[Integer, Integer, Integer] = {
    super.valuesRow.asInstanceOf[ Row3[Integer, Integer, Integer] ]
  }
  override def field1 : Field[Integer] = Userandtextaudioindex.USERANDTEXTAUDIOINDEX.ID
  override def field2 : Field[Integer] = Userandtextaudioindex.USERANDTEXTAUDIOINDEX.USERID
  override def field3 : Field[Integer] = Userandtextaudioindex.USERANDTEXTAUDIOINDEX.TEXTAUDIOINDEXID
  override def component1 : Integer = getId
  override def component2 : Integer = getUserid
  override def component3 : Integer = getTextaudioindexid
  override def value1 : Integer = getId
  override def value2 : Integer = getUserid
  override def value3 : Integer = getTextaudioindexid

  override def value1(value : Integer) : UserandtextaudioindexRecord = {
    setId(value)
    this
  }

  override def value2(value : Integer) : UserandtextaudioindexRecord = {
    setUserid(value)
    this
  }

  override def value3(value : Integer) : UserandtextaudioindexRecord = {
    setTextaudioindexid(value)
    this
  }

  override def values(value1 : Integer, value2 : Integer, value3 : Integer) : UserandtextaudioindexRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this
  }

  def this(id : Integer, userid : Integer, textaudioindexid : Integer) = {
    this()

    set(0, id)
    set(1, userid)
    set(2, textaudioindexid)
  }
}
