/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables.daos


import java.lang.Integer
import java.lang.String
import java.util.List

import jooq.db.tables.Audio
import jooq.db.tables.records.AudioRecord

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


class AudioDao(configuration : Configuration) extends DAOImpl[AudioRecord, jooq.db.tables.pojos.Audio, Integer](Audio.AUDIO, classOf[jooq.db.tables.pojos.Audio], configuration) {

  def this() = {
    this(null)
  }

  override protected def getId(o : jooq.db.tables.pojos.Audio) : Integer = {
    o.getId
  }

  def fetchById(values : Integer*) : List[jooq.db.tables.pojos.Audio] = {
    fetch(Audio.AUDIO.ID, values:_*)
  }

  def fetchOneById(value : Integer) : jooq.db.tables.pojos.Audio = {
    fetchOne(Audio.AUDIO.ID, value)
  }

  def fetchByPath(values : String*) : List[jooq.db.tables.pojos.Audio] = {
    fetch(Audio.AUDIO.PATH, values:_*)
  }

  def fetchByFileid(values : Integer*) : List[jooq.db.tables.pojos.Audio] = {
    fetch(Audio.AUDIO.FILEID, values:_*)
  }
}
