/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables.daos


import java.lang.Integer
import java.lang.Long
import java.util.List

import jooq.db.tables.Avatar
import jooq.db.tables.records.AvatarRecord

import org.jooq.Configuration
import org.jooq.impl.DAOImpl

import scala.Array
import scala.Byte


class AvatarDao(configuration : Configuration) extends DAOImpl[AvatarRecord, jooq.db.tables.pojos.Avatar, Long](Avatar.AVATAR, classOf[jooq.db.tables.pojos.Avatar], configuration) {

  def this() = {
    this(null)
  }

  override protected def getId(o : jooq.db.tables.pojos.Avatar) : Long = {
    o.getId
  }

  def fetchById(values : Long*) : List[jooq.db.tables.pojos.Avatar] = {
    fetch(Avatar.AVATAR.ID, values:_*)
  }

  def fetchOneById(value : Long) : jooq.db.tables.pojos.Avatar = {
    fetchOne(Avatar.AVATAR.ID, value)
  }

  def fetchByUserid(values : Integer*) : List[jooq.db.tables.pojos.Avatar] = {
    fetch(Avatar.AVATAR.USERID, values:_*)
  }

  def fetchOneByUserid(value : Integer) : jooq.db.tables.pojos.Avatar = {
    fetchOne(Avatar.AVATAR.USERID, value)
  }

  def fetchByAvatar(values : Array[Byte]*) : List[jooq.db.tables.pojos.Avatar] = {
    fetch(Avatar.AVATAR.AVATAR_, values:_*)
  }
}
