/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables.daos


import java.lang.Integer
import java.lang.String
import java.util.List

import jooq.db.tables.Chat
import jooq.db.tables.records.ChatRecord

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


class ChatDao(configuration : Configuration) extends DAOImpl[ChatRecord, jooq.db.tables.pojos.Chat, Integer](Chat.CHAT, classOf[jooq.db.tables.pojos.Chat], configuration) {

  def this() = {
    this(null)
  }

  override protected def getId(o : jooq.db.tables.pojos.Chat) : Integer = {
    o.getId
  }

  def fetchById(values : Integer*) : List[jooq.db.tables.pojos.Chat] = {
    fetch(Chat.CHAT.ID, values:_*)
  }

  def fetchOneById(value : Integer) : jooq.db.tables.pojos.Chat = {
    fetchOne(Chat.CHAT.ID, value)
  }

  def fetchByChatname(values : String*) : List[jooq.db.tables.pojos.Chat] = {
    fetch(Chat.CHAT.CHATNAME, values:_*)
  }
}
