/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables.daos


import java.lang.Double
import java.lang.Long
import java.lang.String
import java.util.List

import jooq.db.tables.Textaudio
import jooq.db.tables.records.TextaudioRecord

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


class TextaudioDao(configuration : Configuration) extends DAOImpl[TextaudioRecord, jooq.db.tables.pojos.Textaudio, Long](Textaudio.TEXTAUDIO, classOf[jooq.db.tables.pojos.Textaudio], configuration) {

  def this() = {
    this(null)
  }

  override protected def getId(o : jooq.db.tables.pojos.Textaudio) : Long = {
    o.getId
  }

  def fetchById(values : Long*) : List[jooq.db.tables.pojos.Textaudio] = {
    fetch(Textaudio.TEXTAUDIO.ID, values:_*)
  }

  def fetchOneById(value : Long) : jooq.db.tables.pojos.Textaudio = {
    fetchOne(Textaudio.TEXTAUDIO.ID, value)
  }

  def fetchByAudiostart(values : Double*) : List[jooq.db.tables.pojos.Textaudio] = {
    fetch(Textaudio.TEXTAUDIO.AUDIOSTART, values:_*)
  }

  def fetchByAudioend(values : Double*) : List[jooq.db.tables.pojos.Textaudio] = {
    fetch(Textaudio.TEXTAUDIO.AUDIOEND, values:_*)
  }

  def fetchByText(values : String*) : List[jooq.db.tables.pojos.Textaudio] = {
    fetch(Textaudio.TEXTAUDIO.TEXT, values:_*)
  }

  def fetchByFileid(values : Long*) : List[jooq.db.tables.pojos.Textaudio] = {
    fetch(Textaudio.TEXTAUDIO.FILEID, values:_*)
  }

  def fetchBySpeaker(values : String*) : List[jooq.db.tables.pojos.Textaudio] = {
    fetch(Textaudio.TEXTAUDIO.SPEAKER, values:_*)
  }

  def fetchByLabeled(values : Long*) : List[jooq.db.tables.pojos.Textaudio] = {
    fetch(Textaudio.TEXTAUDIO.LABELED, values:_*)
  }

  def fetchByCorrect(values : Long*) : List[jooq.db.tables.pojos.Textaudio] = {
    fetch(Textaudio.TEXTAUDIO.CORRECT, values:_*)
  }

  def fetchByWrong(values : Long*) : List[jooq.db.tables.pojos.Textaudio] = {
    fetch(Textaudio.TEXTAUDIO.WRONG, values:_*)
  }
}
