/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables.daos


import java.lang.Integer
import java.lang.String
import java.util.List

import jooq.db.tables.User
import jooq.db.tables.records.UserRecord

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


class UserDao(configuration : Configuration) extends DAOImpl[UserRecord, jooq.db.tables.pojos.User, Integer](User.USER, classOf[jooq.db.tables.pojos.User], configuration) {

  def this() = {
    this(null)
  }

  override protected def getId(o : jooq.db.tables.pojos.User) : Integer = {
    o.getId
  }

  def fetchById(values : Integer*) : List[jooq.db.tables.pojos.User] = {
    fetch(User.USER.ID, values:_*)
  }

  def fetchOneById(value : Integer) : jooq.db.tables.pojos.User = {
    fetchOne(User.USER.ID, value)
  }

  def fetchByFirstname(values : String*) : List[jooq.db.tables.pojos.User] = {
    fetch(User.USER.FIRSTNAME, values:_*)
  }

  def fetchByLastname(values : String*) : List[jooq.db.tables.pojos.User] = {
    fetch(User.USER.LASTNAME, values:_*)
  }

  def fetchByEmail(values : String*) : List[jooq.db.tables.pojos.User] = {
    fetch(User.USER.EMAIL, values:_*)
  }

  def fetchOneByEmail(value : String) : jooq.db.tables.pojos.User = {
    fetchOne(User.USER.EMAIL, value)
  }

  def fetchByPassword(values : String*) : List[jooq.db.tables.pojos.User] = {
    fetch(User.USER.PASSWORD, values:_*)
  }
}
