/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables.records


import java.lang.Integer

import jooq.db.tables.Avatar

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record3
import org.jooq.Row3
import org.jooq.impl.UpdatableRecordImpl

import scala.Array
import scala.Byte


class AvatarRecord extends UpdatableRecordImpl[AvatarRecord](Avatar.AVATAR) with Record3[Integer, Integer, Array[Byte]] {

  def setId(value : Integer) : Unit = {
    set(0, value)
  }

  def getId : Integer = {
    val r = get(0)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  def setUserid(value : Integer) : Unit = {
    set(1, value)
  }

  def getUserid : Integer = {
    val r = get(1)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  def setAvatar(value : Array[Byte]) : Unit = {
    set(2, value)
  }

  def getAvatar : Array[Byte] = {
    val r = get(2)
    if (r == null) null else r.asInstanceOf[Array[Byte]]
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------
  override def key : Record1[Integer] = {
    return super.key.asInstanceOf[ Record1[Integer] ]
  }

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow : Row3[Integer, Integer, Array[Byte]] = {
    super.fieldsRow.asInstanceOf[ Row3[Integer, Integer, Array[Byte]] ]
  }

  override def valuesRow : Row3[Integer, Integer, Array[Byte]] = {
    super.valuesRow.asInstanceOf[ Row3[Integer, Integer, Array[Byte]] ]
  }
  override def field1 : Field[Integer] = Avatar.AVATAR.ID
  override def field2 : Field[Integer] = Avatar.AVATAR.USERID
  override def field3 : Field[Array[Byte]] = Avatar.AVATAR.AVATAR_
  override def component1 : Integer = getId
  override def component2 : Integer = getUserid
  override def component3 : Array[Byte] = getAvatar
  override def value1 : Integer = getId
  override def value2 : Integer = getUserid
  override def value3 : Array[Byte] = getAvatar

  override def value1(value : Integer) : AvatarRecord = {
    setId(value)
    this
  }

  override def value2(value : Integer) : AvatarRecord = {
    setUserid(value)
    this
  }

  override def value3(value : Array[Byte]) : AvatarRecord = {
    setAvatar(value)
    this
  }

  override def values(value1 : Integer, value2 : Integer, value3 : Array[Byte]) : AvatarRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this
  }

  def this(id : Integer, userid : Integer, avatar : Array[Byte]) = {
    this()

    set(0, id)
    set(1, userid)
    set(2, avatar)
  }
}
