/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables.records


import java.lang.Integer

import jooq.db.tables.Chatmember

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record3
import org.jooq.Row3
import org.jooq.impl.UpdatableRecordImpl


class ChatmemberRecord extends UpdatableRecordImpl[ChatmemberRecord](Chatmember.CHATMEMBER) with Record3[Integer, Integer, Integer] {

  def setId(value : Integer) : Unit = {
    set(0, value)
  }

  def getId : Integer = {
    val r = get(0)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  def setChatid(value : Integer) : Unit = {
    set(1, value)
  }

  def getChatid : Integer = {
    val r = get(1)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  def setUserid(value : Integer) : Unit = {
    set(2, value)
  }

  def getUserid : Integer = {
    val r = get(2)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------
  override def key : Record1[Integer] = {
    return super.key.asInstanceOf[ Record1[Integer] ]
  }

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow : Row3[Integer, Integer, Integer] = {
    super.fieldsRow.asInstanceOf[ Row3[Integer, Integer, Integer] ]
  }

  override def valuesRow : Row3[Integer, Integer, Integer] = {
    super.valuesRow.asInstanceOf[ Row3[Integer, Integer, Integer] ]
  }
  override def field1 : Field[Integer] = Chatmember.CHATMEMBER.ID
  override def field2 : Field[Integer] = Chatmember.CHATMEMBER.CHATID
  override def field3 : Field[Integer] = Chatmember.CHATMEMBER.USERID
  override def component1 : Integer = getId
  override def component2 : Integer = getChatid
  override def component3 : Integer = getUserid
  override def value1 : Integer = getId
  override def value2 : Integer = getChatid
  override def value3 : Integer = getUserid

  override def value1(value : Integer) : ChatmemberRecord = {
    setId(value)
    this
  }

  override def value2(value : Integer) : ChatmemberRecord = {
    setChatid(value)
    this
  }

  override def value3(value : Integer) : ChatmemberRecord = {
    setUserid(value)
    this
  }

  override def values(value1 : Integer, value2 : Integer, value3 : Integer) : ChatmemberRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this
  }

  def this(id : Integer, chatid : Integer, userid : Integer) = {
    this()

    set(0, id)
    set(1, chatid)
    set(2, userid)
  }
}
