/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables.records


import java.lang.Double
import java.lang.Long
import java.lang.String

import jooq.db.tables.Textaudio

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record9
import org.jooq.Row9
import org.jooq.impl.UpdatableRecordImpl


class TextaudioRecord extends UpdatableRecordImpl[TextaudioRecord](Textaudio.TEXTAUDIO) with Record9[Long, Double, Double, String, Long, String, Long, Long, Long] {

  def setId(value : Long) : Unit = {
    set(0, value)
  }

  def getId : Long = {
    val r = get(0)
    if (r == null) null else r.asInstanceOf[Long]
  }

  def setAudiostart(value : Double) : Unit = {
    set(1, value)
  }

  def getAudiostart : Double = {
    val r = get(1)
    if (r == null) null else r.asInstanceOf[Double]
  }

  def setAudioend(value : Double) : Unit = {
    set(2, value)
  }

  def getAudioend : Double = {
    val r = get(2)
    if (r == null) null else r.asInstanceOf[Double]
  }

  def setText(value : String) : Unit = {
    set(3, value)
  }

  def getText : String = {
    val r = get(3)
    if (r == null) null else r.asInstanceOf[String]
  }

  def setFileid(value : Long) : Unit = {
    set(4, value)
  }

  def getFileid : Long = {
    val r = get(4)
    if (r == null) null else r.asInstanceOf[Long]
  }

  def setSpeaker(value : String) : Unit = {
    set(5, value)
  }

  def getSpeaker : String = {
    val r = get(5)
    if (r == null) null else r.asInstanceOf[String]
  }

  def setLabeled(value : Long) : Unit = {
    set(6, value)
  }

  def getLabeled : Long = {
    val r = get(6)
    if (r == null) null else r.asInstanceOf[Long]
  }

  def setCorrect(value : Long) : Unit = {
    set(7, value)
  }

  def getCorrect : Long = {
    val r = get(7)
    if (r == null) null else r.asInstanceOf[Long]
  }

  def setWrong(value : Long) : Unit = {
    set(8, value)
  }

  def getWrong : Long = {
    val r = get(8)
    if (r == null) null else r.asInstanceOf[Long]
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------
  override def key : Record1[Long] = {
    return super.key.asInstanceOf[ Record1[Long] ]
  }

  // -------------------------------------------------------------------------
  // Record9 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow : Row9[Long, Double, Double, String, Long, String, Long, Long, Long] = {
    super.fieldsRow.asInstanceOf[ Row9[Long, Double, Double, String, Long, String, Long, Long, Long] ]
  }

  override def valuesRow : Row9[Long, Double, Double, String, Long, String, Long, Long, Long] = {
    super.valuesRow.asInstanceOf[ Row9[Long, Double, Double, String, Long, String, Long, Long, Long] ]
  }
  override def field1 : Field[Long] = Textaudio.TEXTAUDIO.ID
  override def field2 : Field[Double] = Textaudio.TEXTAUDIO.AUDIOSTART
  override def field3 : Field[Double] = Textaudio.TEXTAUDIO.AUDIOEND
  override def field4 : Field[String] = Textaudio.TEXTAUDIO.TEXT
  override def field5 : Field[Long] = Textaudio.TEXTAUDIO.FILEID
  override def field6 : Field[String] = Textaudio.TEXTAUDIO.SPEAKER
  override def field7 : Field[Long] = Textaudio.TEXTAUDIO.LABELED
  override def field8 : Field[Long] = Textaudio.TEXTAUDIO.CORRECT
  override def field9 : Field[Long] = Textaudio.TEXTAUDIO.WRONG
  override def component1 : Long = getId
  override def component2 : Double = getAudiostart
  override def component3 : Double = getAudioend
  override def component4 : String = getText
  override def component5 : Long = getFileid
  override def component6 : String = getSpeaker
  override def component7 : Long = getLabeled
  override def component8 : Long = getCorrect
  override def component9 : Long = getWrong
  override def value1 : Long = getId
  override def value2 : Double = getAudiostart
  override def value3 : Double = getAudioend
  override def value4 : String = getText
  override def value5 : Long = getFileid
  override def value6 : String = getSpeaker
  override def value7 : Long = getLabeled
  override def value8 : Long = getCorrect
  override def value9 : Long = getWrong

  override def value1(value : Long) : TextaudioRecord = {
    setId(value)
    this
  }

  override def value2(value : Double) : TextaudioRecord = {
    setAudiostart(value)
    this
  }

  override def value3(value : Double) : TextaudioRecord = {
    setAudioend(value)
    this
  }

  override def value4(value : String) : TextaudioRecord = {
    setText(value)
    this
  }

  override def value5(value : Long) : TextaudioRecord = {
    setFileid(value)
    this
  }

  override def value6(value : String) : TextaudioRecord = {
    setSpeaker(value)
    this
  }

  override def value7(value : Long) : TextaudioRecord = {
    setLabeled(value)
    this
  }

  override def value8(value : Long) : TextaudioRecord = {
    setCorrect(value)
    this
  }

  override def value9(value : Long) : TextaudioRecord = {
    setWrong(value)
    this
  }

  override def values(value1 : Long, value2 : Double, value3 : Double, value4 : String, value5 : Long, value6 : String, value7 : Long, value8 : Long, value9 : Long) : TextaudioRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this.value5(value5)
    this.value6(value6)
    this.value7(value7)
    this.value8(value8)
    this.value9(value9)
    this
  }

  def this(id : Long, audiostart : Double, audioend : Double, text : String, fileid : Long, speaker : String, labeled : Long, correct : Long, wrong : Long) = {
    this()

    set(0, id)
    set(1, audiostart)
    set(2, audioend)
    set(3, text)
    set(4, fileid)
    set(5, speaker)
    set(6, labeled)
    set(7, correct)
    set(8, wrong)
  }
}
