/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables.records


import java.lang.Integer

import jooq.db.tables.Textaudioindex

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record7
import org.jooq.Row7
import org.jooq.impl.UpdatableRecordImpl


class TextaudioindexRecord extends UpdatableRecordImpl[TextaudioindexRecord](Textaudioindex.TEXTAUDIOINDEX) with Record7[Integer, Integer, Integer, Integer, Integer, Integer, Integer] {

  def setId(value : Integer) : Unit = {
    set(0, value)
  }

  def getId : Integer = {
    val r = get(0)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  def setSamplingrate(value : Integer) : Unit = {
    set(1, value)
  }

  def getSamplingrate : Integer = {
    val r = get(1)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  def setTextstartpos(value : Integer) : Unit = {
    set(2, value)
  }

  def getTextstartpos : Integer = {
    val r = get(2)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  def setTextendpos(value : Integer) : Unit = {
    set(3, value)
  }

  def getTextendpos : Integer = {
    val r = get(3)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  def setAudiostartpos(value : Integer) : Unit = {
    set(4, value)
  }

  def getAudiostartpos : Integer = {
    val r = get(4)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  def setAudioendpos(value : Integer) : Unit = {
    set(5, value)
  }

  def getAudioendpos : Integer = {
    val r = get(5)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  def setSpeakerkey(value : Integer) : Unit = {
    set(6, value)
  }

  def getSpeakerkey : Integer = {
    val r = get(6)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------
  override def key : Record1[Integer] = {
    return super.key.asInstanceOf[ Record1[Integer] ]
  }

  // -------------------------------------------------------------------------
  // Record7 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow : Row7[Integer, Integer, Integer, Integer, Integer, Integer, Integer] = {
    super.fieldsRow.asInstanceOf[ Row7[Integer, Integer, Integer, Integer, Integer, Integer, Integer] ]
  }

  override def valuesRow : Row7[Integer, Integer, Integer, Integer, Integer, Integer, Integer] = {
    super.valuesRow.asInstanceOf[ Row7[Integer, Integer, Integer, Integer, Integer, Integer, Integer] ]
  }
  override def field1 : Field[Integer] = Textaudioindex.TEXTAUDIOINDEX.ID
  override def field2 : Field[Integer] = Textaudioindex.TEXTAUDIOINDEX.SAMPLINGRATE
  override def field3 : Field[Integer] = Textaudioindex.TEXTAUDIOINDEX.TEXTSTARTPOS
  override def field4 : Field[Integer] = Textaudioindex.TEXTAUDIOINDEX.TEXTENDPOS
  override def field5 : Field[Integer] = Textaudioindex.TEXTAUDIOINDEX.AUDIOSTARTPOS
  override def field6 : Field[Integer] = Textaudioindex.TEXTAUDIOINDEX.AUDIOENDPOS
  override def field7 : Field[Integer] = Textaudioindex.TEXTAUDIOINDEX.SPEAKERKEY
  override def component1 : Integer = getId
  override def component2 : Integer = getSamplingrate
  override def component3 : Integer = getTextstartpos
  override def component4 : Integer = getTextendpos
  override def component5 : Integer = getAudiostartpos
  override def component6 : Integer = getAudioendpos
  override def component7 : Integer = getSpeakerkey
  override def value1 : Integer = getId
  override def value2 : Integer = getSamplingrate
  override def value3 : Integer = getTextstartpos
  override def value4 : Integer = getTextendpos
  override def value5 : Integer = getAudiostartpos
  override def value6 : Integer = getAudioendpos
  override def value7 : Integer = getSpeakerkey

  override def value1(value : Integer) : TextaudioindexRecord = {
    setId(value)
    this
  }

  override def value2(value : Integer) : TextaudioindexRecord = {
    setSamplingrate(value)
    this
  }

  override def value3(value : Integer) : TextaudioindexRecord = {
    setTextstartpos(value)
    this
  }

  override def value4(value : Integer) : TextaudioindexRecord = {
    setTextendpos(value)
    this
  }

  override def value5(value : Integer) : TextaudioindexRecord = {
    setAudiostartpos(value)
    this
  }

  override def value6(value : Integer) : TextaudioindexRecord = {
    setAudioendpos(value)
    this
  }

  override def value7(value : Integer) : TextaudioindexRecord = {
    setSpeakerkey(value)
    this
  }

  override def values(value1 : Integer, value2 : Integer, value3 : Integer, value4 : Integer, value5 : Integer, value6 : Integer, value7 : Integer) : TextaudioindexRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this.value5(value5)
    this.value6(value6)
    this.value7(value7)
    this
  }

  def this(id : Integer, samplingrate : Integer, textstartpos : Integer, textendpos : Integer, audiostartpos : Integer, audioendpos : Integer, speakerkey : Integer) = {
    this()

    set(0, id)
    set(1, samplingrate)
    set(2, textstartpos)
    set(3, textendpos)
    set(4, audiostartpos)
    set(5, audioendpos)
    set(6, speakerkey)
  }
}
