/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables.records


import java.lang.Integer
import java.lang.String

import jooq.db.tables.Transcript

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record2
import org.jooq.Row2
import org.jooq.impl.UpdatableRecordImpl


class TranscriptRecord extends UpdatableRecordImpl[TranscriptRecord](Transcript.TRANSCRIPT) with Record2[Integer, String] {

  def setId(value : Integer) : Unit = {
    set(0, value)
  }

  def getId : Integer = {
    val r = get(0)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  def setText(value : String) : Unit = {
    set(1, value)
  }

  def getText : String = {
    val r = get(1)
    if (r == null) null else r.asInstanceOf[String]
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------
  override def key : Record1[Integer] = {
    return super.key.asInstanceOf[ Record1[Integer] ]
  }

  // -------------------------------------------------------------------------
  // Record2 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow : Row2[Integer, String] = {
    super.fieldsRow.asInstanceOf[ Row2[Integer, String] ]
  }

  override def valuesRow : Row2[Integer, String] = {
    super.valuesRow.asInstanceOf[ Row2[Integer, String] ]
  }
  override def field1 : Field[Integer] = Transcript.TRANSCRIPT.ID
  override def field2 : Field[String] = Transcript.TRANSCRIPT.TEXT
  override def component1 : Integer = getId
  override def component2 : String = getText
  override def value1 : Integer = getId
  override def value2 : String = getText

  override def value1(value : Integer) : TranscriptRecord = {
    setId(value)
    this
  }

  override def value2(value : String) : TranscriptRecord = {
    setText(value)
    this
  }

  override def values(value1 : Integer, value2 : String) : TranscriptRecord = {
    this.value1(value1)
    this.value2(value2)
    this
  }

  def this(id : Integer, text : String) = {
    this()

    set(0, id)
    set(1, text)
  }
}
