/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables.records


import java.lang.Integer
import java.lang.String

import jooq.db.tables.User

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record8
import org.jooq.Row8
import org.jooq.impl.UpdatableRecordImpl


class UserRecord extends UpdatableRecordImpl[UserRecord](User.USER) with Record8[Integer, String, String, String, String, Integer, String, String] {

  def setId(value : Integer) : Unit = {
    set(0, value)
  }

  def getId : Integer = {
    val r = get(0)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  def setFirstname(value : String) : Unit = {
    set(1, value)
  }

  def getFirstname : String = {
    val r = get(1)
    if (r == null) null else r.asInstanceOf[String]
  }

  def setLastname(value : String) : Unit = {
    set(2, value)
  }

  def getLastname : String = {
    val r = get(2)
    if (r == null) null else r.asInstanceOf[String]
  }

  def setEmail(value : String) : Unit = {
    set(3, value)
  }

  def getEmail : String = {
    val r = get(3)
    if (r == null) null else r.asInstanceOf[String]
  }

  def setUsername(value : String) : Unit = {
    set(4, value)
  }

  def getUsername : String = {
    val r = get(4)
    if (r == null) null else r.asInstanceOf[String]
  }

  def setAvatarversion(value : Integer) : Unit = {
    set(5, value)
  }

  def getAvatarversion : Integer = {
    val r = get(5)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  def setPassword(value : String) : Unit = {
    set(6, value)
  }

  def getPassword : String = {
    val r = get(6)
    if (r == null) null else r.asInstanceOf[String]
  }

  def setCanton(value : String) : Unit = {
    set(7, value)
  }

  def getCanton : String = {
    val r = get(7)
    if (r == null) null else r.asInstanceOf[String]
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------
  override def key : Record1[Integer] = {
    return super.key.asInstanceOf[ Record1[Integer] ]
  }

  // -------------------------------------------------------------------------
  // Record8 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow : Row8[Integer, String, String, String, String, Integer, String, String] = {
    super.fieldsRow.asInstanceOf[ Row8[Integer, String, String, String, String, Integer, String, String] ]
  }

  override def valuesRow : Row8[Integer, String, String, String, String, Integer, String, String] = {
    super.valuesRow.asInstanceOf[ Row8[Integer, String, String, String, String, Integer, String, String] ]
  }
  override def field1 : Field[Integer] = User.USER.ID
  override def field2 : Field[String] = User.USER.FIRSTNAME
  override def field3 : Field[String] = User.USER.LASTNAME
  override def field4 : Field[String] = User.USER.EMAIL
  override def field5 : Field[String] = User.USER.USERNAME
  override def field6 : Field[Integer] = User.USER.AVATARVERSION
  override def field7 : Field[String] = User.USER.PASSWORD
  override def field8 : Field[String] = User.USER.CANTON
  override def component1 : Integer = getId
  override def component2 : String = getFirstname
  override def component3 : String = getLastname
  override def component4 : String = getEmail
  override def component5 : String = getUsername
  override def component6 : Integer = getAvatarversion
  override def component7 : String = getPassword
  override def component8 : String = getCanton
  override def value1 : Integer = getId
  override def value2 : String = getFirstname
  override def value3 : String = getLastname
  override def value4 : String = getEmail
  override def value5 : String = getUsername
  override def value6 : Integer = getAvatarversion
  override def value7 : String = getPassword
  override def value8 : String = getCanton

  override def value1(value : Integer) : UserRecord = {
    setId(value)
    this
  }

  override def value2(value : String) : UserRecord = {
    setFirstname(value)
    this
  }

  override def value3(value : String) : UserRecord = {
    setLastname(value)
    this
  }

  override def value4(value : String) : UserRecord = {
    setEmail(value)
    this
  }

  override def value5(value : String) : UserRecord = {
    setUsername(value)
    this
  }

  override def value6(value : Integer) : UserRecord = {
    setAvatarversion(value)
    this
  }

  override def value7(value : String) : UserRecord = {
    setPassword(value)
    this
  }

  override def value8(value : String) : UserRecord = {
    setCanton(value)
    this
  }

  override def values(value1 : Integer, value2 : String, value3 : String, value4 : String, value5 : String, value6 : Integer, value7 : String, value8 : String) : UserRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this.value5(value5)
    this.value6(value6)
    this.value7(value7)
    this.value8(value8)
    this
  }

  def this(id : Integer, firstname : String, lastname : String, email : String, username : String, avatarversion : Integer, password : String, canton : String) = {
    this()

    set(0, id)
    set(1, firstname)
    set(2, lastname)
    set(3, email)
    set(4, username)
    set(5, avatarversion)
    set(6, password)
    set(7, canton)
  }
}
