/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables.records


import java.lang.Long
import java.lang.String

import jooq.db.tables.Userandtextaudio

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record4
import org.jooq.Row4
import org.jooq.impl.UpdatableRecordImpl


class UserandtextaudioRecord extends UpdatableRecordImpl[UserandtextaudioRecord](Userandtextaudio.USERANDTEXTAUDIO) with Record4[Long, String, String, String] {

  def setId(value : Long) : Unit = {
    set(0, value)
  }

  def getId : Long = {
    val r = get(0)
    if (r == null) null else r.asInstanceOf[Long]
  }

  def setUserid(value : String) : Unit = {
    set(1, value)
  }

  def getUserid : String = {
    val r = get(1)
    if (r == null) null else r.asInstanceOf[String]
  }

  def setTextaudioid(value : String) : Unit = {
    set(2, value)
  }

  def getTextaudioid : String = {
    val r = get(2)
    if (r == null) null else r.asInstanceOf[String]
  }

  def setTime(value : String) : Unit = {
    set(3, value)
  }

  def getTime : String = {
    val r = get(3)
    if (r == null) null else r.asInstanceOf[String]
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------
  override def key : Record1[Long] = {
    return super.key.asInstanceOf[ Record1[Long] ]
  }

  // -------------------------------------------------------------------------
  // Record4 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow : Row4[Long, String, String, String] = {
    super.fieldsRow.asInstanceOf[ Row4[Long, String, String, String] ]
  }

  override def valuesRow : Row4[Long, String, String, String] = {
    super.valuesRow.asInstanceOf[ Row4[Long, String, String, String] ]
  }
  override def field1 : Field[Long] = Userandtextaudio.USERANDTEXTAUDIO.ID
  override def field2 : Field[String] = Userandtextaudio.USERANDTEXTAUDIO.USERID
  override def field3 : Field[String] = Userandtextaudio.USERANDTEXTAUDIO.TEXTAUDIOID
  override def field4 : Field[String] = Userandtextaudio.USERANDTEXTAUDIO.TIME
  override def component1 : Long = getId
  override def component2 : String = getUserid
  override def component3 : String = getTextaudioid
  override def component4 : String = getTime
  override def value1 : Long = getId
  override def value2 : String = getUserid
  override def value3 : String = getTextaudioid
  override def value4 : String = getTime

  override def value1(value : Long) : UserandtextaudioRecord = {
    setId(value)
    this
  }

  override def value2(value : String) : UserandtextaudioRecord = {
    setUserid(value)
    this
  }

  override def value3(value : String) : UserandtextaudioRecord = {
    setTextaudioid(value)
    this
  }

  override def value4(value : String) : UserandtextaudioRecord = {
    setTime(value)
    this
  }

  override def values(value1 : Long, value2 : String, value3 : String, value4 : String) : UserandtextaudioRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this
  }

  def this(id : Long, userid : String, textaudioid : String, time : String) = {
    this()

    set(0, id)
    set(1, userid)
    set(2, textaudioid)
    set(3, time)
  }
}
