/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables


import java.lang.Class
import java.lang.Double
import java.lang.Integer
import java.lang.String
import java.util.Arrays
import java.util.List

import jooq.db.Indexes
import jooq.db.Keys
import jooq.db.LabelingTool
import jooq.db.tables.records.MatchRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.TableImpl

import scala.Array


object Match {

  val MATCH = new Match
}

class Match(
  alias : Name,
  child : Table[_ <: Record],
  path : ForeignKey[_ <: Record, MatchRecord],
  aliased : Table[MatchRecord],
  parameters : Array[ Field[_] ]
)
extends TableImpl[MatchRecord](
  alias,
  LabelingTool.LABELING_TOOL,
  child,
  path,
  aliased,
  parameters,
  DSL.comment("")
)
{

  override def getRecordType : Class[MatchRecord] = {
    classOf[MatchRecord]
  }

  val MATCHID : TableField[MatchRecord, Integer] = createField("matchId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), "")

  val AUDIOSTART : TableField[MatchRecord, Double] = createField("audioStart", org.jooq.impl.SQLDataType.DOUBLE, "")

  val AUDIOEND : TableField[MatchRecord, Double] = createField("audioEnd", org.jooq.impl.SQLDataType.DOUBLE, "")

  val TEXTSTART : TableField[MatchRecord, Double] = createField("textStart", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), "")

  val TEXTEND : TableField[MatchRecord, Double] = createField("textEnd", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), "")

  def this() = {
    this(DSL.name("match"), null, null, null, null)
  }

  def this(alias : String) = {
    this(DSL.name(alias), null, null, jooq.db.tables.Match.MATCH, null)
  }

  def this(alias : Name) = {
    this(alias, null, null, jooq.db.tables.Match.MATCH, null)
  }

  private def this(alias : Name, aliased : Table[MatchRecord]) = {
    this(alias, null, null, aliased, null)
  }

  def this(child : Table[_ <: Record], key : ForeignKey[_ <: Record, MatchRecord]) = {
    this(Internal.createPathAlias(child, key), child, key, jooq.db.tables.Match.MATCH, null)
  }

  override def getSchema : Schema = LabelingTool.LABELING_TOOL

  override def getIndexes : List[ Index ] = {
    return Arrays.asList[ Index ](Indexes.MATCH_PRIMARY)
  }

  override def getIdentity : Identity[MatchRecord, Integer] = {
    Keys.IDENTITY_MATCH
  }

  override def getPrimaryKey : UniqueKey[MatchRecord] = {
    Keys.KEY_MATCH_PRIMARY
  }

  override def getKeys : List[ UniqueKey[MatchRecord] ] = {
    return Arrays.asList[ UniqueKey[MatchRecord] ](Keys.KEY_MATCH_PRIMARY)
  }

  override def as(alias : String) : Match = {
    new Match(DSL.name(alias), this)
  }

  override def as(alias : Name) : Match = {
    new Match(alias, this)
  }

  override def rename(name : String) : Match = {
    new Match(DSL.name(name), null)
  }

  override def rename(name : Name) : Match = {
    new Match(name, null)
  }
}
