/*
 * This file is generated by jOOQ.
 */
package jooq.db.tables


import java.lang.Class
import java.lang.Long
import java.lang.String
import java.util.Arrays
import java.util.List

import jooq.db.Indexes
import jooq.db.Keys
import jooq.db.LabelingTool
import jooq.db.tables.records.SpeakerRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.TableImpl

import scala.Array


object Speaker {

  val SPEAKER = new Speaker
}

class Speaker(
  alias : Name,
  child : Table[_ <: Record],
  path : ForeignKey[_ <: Record, SpeakerRecord],
  aliased : Table[SpeakerRecord],
  parameters : Array[ Field[_] ]
)
extends TableImpl[SpeakerRecord](
  alias,
  LabelingTool.LABELING_TOOL,
  child,
  path,
  aliased,
  parameters,
  DSL.comment("")
)
{

  override def getRecordType : Class[SpeakerRecord] = {
    classOf[SpeakerRecord]
  }

  val ID : TableField[SpeakerRecord, Long] = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), "")

  val SPEAKERID : TableField[SpeakerRecord, String] = createField("speakerId", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), "")

  val SEX : TableField[SpeakerRecord, String] = createField("sex", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), "")

  val LANGUAGEUSED : TableField[SpeakerRecord, String] = createField("languageUsed", org.jooq.impl.SQLDataType.VARCHAR(45).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), "")

  val DIALECT : TableField[SpeakerRecord, String] = createField("dialect", org.jooq.impl.SQLDataType.VARCHAR(45).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), "")

  def this() = {
    this(DSL.name("speaker"), null, null, null, null)
  }

  def this(alias : String) = {
    this(DSL.name(alias), null, null, jooq.db.tables.Speaker.SPEAKER, null)
  }

  def this(alias : Name) = {
    this(alias, null, null, jooq.db.tables.Speaker.SPEAKER, null)
  }

  private def this(alias : Name, aliased : Table[SpeakerRecord]) = {
    this(alias, null, null, aliased, null)
  }

  def this(child : Table[_ <: Record], key : ForeignKey[_ <: Record, SpeakerRecord]) = {
    this(Internal.createPathAlias(child, key), child, key, jooq.db.tables.Speaker.SPEAKER, null)
  }

  override def getSchema : Schema = LabelingTool.LABELING_TOOL

  override def getIndexes : List[ Index ] = {
    return Arrays.asList[ Index ](Indexes.SPEAKER_PRIMARY)
  }

  override def getIdentity : Identity[SpeakerRecord, Long] = {
    Keys.IDENTITY_SPEAKER
  }

  override def getPrimaryKey : UniqueKey[SpeakerRecord] = {
    Keys.KEY_SPEAKER_PRIMARY
  }

  override def getKeys : List[ UniqueKey[SpeakerRecord] ] = {
    return Arrays.asList[ UniqueKey[SpeakerRecord] ](Keys.KEY_SPEAKER_PRIMARY)
  }

  override def as(alias : String) : Speaker = {
    new Speaker(DSL.name(alias), this)
  }

  override def as(alias : Name) : Speaker = {
    new Speaker(alias, this)
  }

  override def rename(name : String) : Speaker = {
    new Speaker(DSL.name(name), null)
  }

  override def rename(name : Name) : Speaker = {
    new Speaker(name, null)
  }
}
