/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.tables.records;


import ch.fhnw.labeling_tool.jooq.enums.CheckedUtteranceLabel;
import ch.fhnw.labeling_tool.jooq.tables.CheckedUtterance;

import java.sql.Timestamp;

import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckedUtteranceRecord extends UpdatableRecordImpl<CheckedUtteranceRecord> implements Record5<Long, Long, Long, CheckedUtteranceLabel, Timestamp> {

    private static final long serialVersionUID = -2046476303;

    public void setId(Long value) {
        set(0, value);
    }

    public Long getId() {
        return (Long) get(0);
    }

    public void setUtteranceId(Long value) {
        set(1, value);
    }

    @NotNull
    public Long getUtteranceId() {
        return (Long) get(1);
    }

    public void setUserId(Long value) {
        set(2, value);
    }

    @NotNull
    public Long getUserId() {
        return (Long) get(2);
    }

    public void setLabel(CheckedUtteranceLabel value) {
        set(3, value);
    }

    public CheckedUtteranceLabel getLabel() {
        return (CheckedUtteranceLabel) get(3);
    }

    public void setTime(Timestamp value) {
        set(4, value);
    }

    public Timestamp getTime() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, CheckedUtteranceLabel, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, Long, CheckedUtteranceLabel, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return CheckedUtterance.CHECKED_UTTERANCE.ID;
    }

    @Override
    public Field<Long> field2() {
        return CheckedUtterance.CHECKED_UTTERANCE.UTTERANCE_ID;
    }

    @Override
    public Field<Long> field3() {
        return CheckedUtterance.CHECKED_UTTERANCE.USER_ID;
    }

    @Override
    public Field<CheckedUtteranceLabel> field4() {
        return CheckedUtterance.CHECKED_UTTERANCE.LABEL;
    }

    @Override
    public Field<Timestamp> field5() {
        return CheckedUtterance.CHECKED_UTTERANCE.TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUtteranceId();
    }

    @Override
    public Long component3() {
        return getUserId();
    }

    @Override
    public CheckedUtteranceLabel component4() {
        return getLabel();
    }

    @Override
    public Timestamp component5() {
        return getTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUtteranceId();
    }

    @Override
    public Long value3() {
        return getUserId();
    }

    @Override
    public CheckedUtteranceLabel value4() {
        return getLabel();
    }

    @Override
    public Timestamp value5() {
        return getTime();
    }

    @Override
    public CheckedUtteranceRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CheckedUtteranceRecord value2(Long value) {
        setUtteranceId(value);
        return this;
    }

    @Override
    public CheckedUtteranceRecord value3(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public CheckedUtteranceRecord value4(CheckedUtteranceLabel value) {
        setLabel(value);
        return this;
    }

    @Override
    public CheckedUtteranceRecord value5(Timestamp value) {
        setTime(value);
        return this;
    }

    @Override
    public CheckedUtteranceRecord values(Long value1, Long value2, Long value3, CheckedUtteranceLabel value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public CheckedUtteranceRecord() {
        super(CheckedUtterance.CHECKED_UTTERANCE);
    }

    public CheckedUtteranceRecord(Long id, Long utteranceId, Long userId, CheckedUtteranceLabel label, Timestamp time) {
        super(CheckedUtterance.CHECKED_UTTERANCE);

        set(0, id);
        set(1, utteranceId);
        set(2, userId);
        set(3, label);
        set(4, time);
    }
}
