/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.tables.records;


import ch.fhnw.labeling_tool.jooq.tables.TextAudio;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TextAudioRecord extends UpdatableRecordImpl<TextAudioRecord> implements Record9<Long, Double, Double, String, Integer, String, Integer, Long, Long> {

    private static final long serialVersionUID = -125761181;

    public void setId(Long value) {
        set(0, value);
    }

    public Long getId() {
        return (Long) get(0);
    }

    public void setAudioStart(Double value) {
        set(1, value);
    }

    @NotNull
    public Double getAudioStart() {
        return (Double) get(1);
    }

    public void setAudioEnd(Double value) {
        set(2, value);
    }

    @NotNull
    public Double getAudioEnd() {
        return (Double) get(2);
    }

    public void setText(String value) {
        set(3, value);
    }

    @Size(max = 16777215)
    public String getText() {
        return (String) get(3);
    }

    public void setFileid(Integer value) {
        set(4, value);
    }

    @NotNull
    public Integer getFileid() {
        return (Integer) get(4);
    }

    public void setSpeaker(String value) {
        set(5, value);
    }

    @Size(max = 45)
    public String getSpeaker() {
        return (String) get(5);
    }

    public void setLabeled(Integer value) {
        set(6, value);
    }

    public Integer getLabeled() {
        return (Integer) get(6);
    }

    public void setCorrect(Long value) {
        set(7, value);
    }

    public Long getCorrect() {
        return (Long) get(7);
    }

    public void setWrong(Long value) {
        set(8, value);
    }

    public Long getWrong() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Double, Double, String, Integer, String, Integer, Long, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, Double, Double, String, Integer, String, Integer, Long, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TextAudio.TEXT_AUDIO.ID;
    }

    @Override
    public Field<Double> field2() {
        return TextAudio.TEXT_AUDIO.AUDIO_START;
    }

    @Override
    public Field<Double> field3() {
        return TextAudio.TEXT_AUDIO.AUDIO_END;
    }

    @Override
    public Field<String> field4() {
        return TextAudio.TEXT_AUDIO.TEXT;
    }

    @Override
    public Field<Integer> field5() {
        return TextAudio.TEXT_AUDIO.FILEID;
    }

    @Override
    public Field<String> field6() {
        return TextAudio.TEXT_AUDIO.SPEAKER;
    }

    @Override
    public Field<Integer> field7() {
        return TextAudio.TEXT_AUDIO.LABELED;
    }

    @Override
    public Field<Long> field8() {
        return TextAudio.TEXT_AUDIO.CORRECT;
    }

    @Override
    public Field<Long> field9() {
        return TextAudio.TEXT_AUDIO.WRONG;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Double component2() {
        return getAudioStart();
    }

    @Override
    public Double component3() {
        return getAudioEnd();
    }

    @Override
    public String component4() {
        return getText();
    }

    @Override
    public Integer component5() {
        return getFileid();
    }

    @Override
    public String component6() {
        return getSpeaker();
    }

    @Override
    public Integer component7() {
        return getLabeled();
    }

    @Override
    public Long component8() {
        return getCorrect();
    }

    @Override
    public Long component9() {
        return getWrong();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Double value2() {
        return getAudioStart();
    }

    @Override
    public Double value3() {
        return getAudioEnd();
    }

    @Override
    public String value4() {
        return getText();
    }

    @Override
    public Integer value5() {
        return getFileid();
    }

    @Override
    public String value6() {
        return getSpeaker();
    }

    @Override
    public Integer value7() {
        return getLabeled();
    }

    @Override
    public Long value8() {
        return getCorrect();
    }

    @Override
    public Long value9() {
        return getWrong();
    }

    @Override
    public TextAudioRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TextAudioRecord value2(Double value) {
        setAudioStart(value);
        return this;
    }

    @Override
    public TextAudioRecord value3(Double value) {
        setAudioEnd(value);
        return this;
    }

    @Override
    public TextAudioRecord value4(String value) {
        setText(value);
        return this;
    }

    @Override
    public TextAudioRecord value5(Integer value) {
        setFileid(value);
        return this;
    }

    @Override
    public TextAudioRecord value6(String value) {
        setSpeaker(value);
        return this;
    }

    @Override
    public TextAudioRecord value7(Integer value) {
        setLabeled(value);
        return this;
    }

    @Override
    public TextAudioRecord value8(Long value) {
        setCorrect(value);
        return this;
    }

    @Override
    public TextAudioRecord value9(Long value) {
        setWrong(value);
        return this;
    }

    @Override
    public TextAudioRecord values(Long value1, Double value2, Double value3, String value4, Integer value5, String value6, Integer value7, Long value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public TextAudioRecord() {
        super(TextAudio.TEXT_AUDIO);
    }

    public TextAudioRecord(Long id, Double audioStart, Double audioEnd, String text, Integer fileid, String speaker, Integer labeled, Long correct, Long wrong) {
        super(TextAudio.TEXT_AUDIO);

        set(0, id);
        set(1, audioStart);
        set(2, audioEnd);
        set(3, text);
        set(4, fileid);
        set(5, speaker);
        set(6, labeled);
        set(7, correct);
        set(8, wrong);
    }
}
