/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.tables.records;


import ch.fhnw.labeling_tool.jooq.tables.TextAudio;

import java.sql.Timestamp;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TextAudioRecord extends UpdatableRecordImpl<TextAudioRecord> implements Record10<Long, Double, Double, String, String, Long, Long, Long, Long, Timestamp> {

    private static final long serialVersionUID = -2070308744;

    public void setId(Long value) {
        set(0, value);
    }

    public Long getId() {
        return (Long) get(0);
    }

    public void setAudioStart(Double value) {
        set(1, value);
    }

    @NotNull
    public Double getAudioStart() {
        return (Double) get(1);
    }

    public void setAudioEnd(Double value) {
        set(2, value);
    }

    @NotNull
    public Double getAudioEnd() {
        return (Double) get(2);
    }

    public void setText(String value) {
        set(3, value);
    }

    @NotNull
    @Size(max = 65535)
    public String getText() {
        return (String) get(3);
    }

    public void setPathToFile(String value) {
        set(4, value);
    }

    @Size(max = 255)
    public String getPathToFile() {
        return (String) get(4);
    }

    public void setSpeakerId(Long value) {
        set(5, value);
    }

    @NotNull
    public Long getSpeakerId() {
        return (Long) get(5);
    }

    public void setSourceId(Long value) {
        set(6, value);
    }

    @NotNull
    public Long getSourceId() {
        return (Long) get(6);
    }

    public void setWrong(Long value) {
        set(7, value);
    }

    public Long getWrong() {
        return (Long) get(7);
    }

    public void setCorrect(Long value) {
        set(8, value);
    }

    public Long getCorrect() {
        return (Long) get(8);
    }

    public void setDeleted(Timestamp value) {
        set(9, value);
    }

    public Timestamp getDeleted() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, Double, Double, String, String, Long, Long, Long, Long, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, Double, Double, String, String, Long, Long, Long, Long, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TextAudio.TEXT_AUDIO.ID;
    }

    @Override
    public Field<Double> field2() {
        return TextAudio.TEXT_AUDIO.AUDIO_START;
    }

    @Override
    public Field<Double> field3() {
        return TextAudio.TEXT_AUDIO.AUDIO_END;
    }

    @Override
    public Field<String> field4() {
        return TextAudio.TEXT_AUDIO.TEXT;
    }

    @Override
    public Field<String> field5() {
        return TextAudio.TEXT_AUDIO.PATH_TO_FILE;
    }

    @Override
    public Field<Long> field6() {
        return TextAudio.TEXT_AUDIO.SPEAKER_ID;
    }

    @Override
    public Field<Long> field7() {
        return TextAudio.TEXT_AUDIO.SOURCE_ID;
    }

    @Override
    public Field<Long> field8() {
        return TextAudio.TEXT_AUDIO.WRONG;
    }

    @Override
    public Field<Long> field9() {
        return TextAudio.TEXT_AUDIO.CORRECT;
    }

    @Override
    public Field<Timestamp> field10() {
        return TextAudio.TEXT_AUDIO.DELETED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Double component2() {
        return getAudioStart();
    }

    @Override
    public Double component3() {
        return getAudioEnd();
    }

    @Override
    public String component4() {
        return getText();
    }

    @Override
    public String component5() {
        return getPathToFile();
    }

    @Override
    public Long component6() {
        return getSpeakerId();
    }

    @Override
    public Long component7() {
        return getSourceId();
    }

    @Override
    public Long component8() {
        return getWrong();
    }

    @Override
    public Long component9() {
        return getCorrect();
    }

    @Override
    public Timestamp component10() {
        return getDeleted();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Double value2() {
        return getAudioStart();
    }

    @Override
    public Double value3() {
        return getAudioEnd();
    }

    @Override
    public String value4() {
        return getText();
    }

    @Override
    public String value5() {
        return getPathToFile();
    }

    @Override
    public Long value6() {
        return getSpeakerId();
    }

    @Override
    public Long value7() {
        return getSourceId();
    }

    @Override
    public Long value8() {
        return getWrong();
    }

    @Override
    public Long value9() {
        return getCorrect();
    }

    @Override
    public Timestamp value10() {
        return getDeleted();
    }

    @Override
    public TextAudioRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TextAudioRecord value2(Double value) {
        setAudioStart(value);
        return this;
    }

    @Override
    public TextAudioRecord value3(Double value) {
        setAudioEnd(value);
        return this;
    }

    @Override
    public TextAudioRecord value4(String value) {
        setText(value);
        return this;
    }

    @Override
    public TextAudioRecord value5(String value) {
        setPathToFile(value);
        return this;
    }

    @Override
    public TextAudioRecord value6(Long value) {
        setSpeakerId(value);
        return this;
    }

    @Override
    public TextAudioRecord value7(Long value) {
        setSourceId(value);
        return this;
    }

    @Override
    public TextAudioRecord value8(Long value) {
        setWrong(value);
        return this;
    }

    @Override
    public TextAudioRecord value9(Long value) {
        setCorrect(value);
        return this;
    }

    @Override
    public TextAudioRecord value10(Timestamp value) {
        setDeleted(value);
        return this;
    }

    @Override
    public TextAudioRecord values(Long value1, Double value2, Double value3, String value4, String value5, Long value6, Long value7, Long value8, Long value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public TextAudioRecord() {
        super(TextAudio.TEXT_AUDIO);
    }

    public TextAudioRecord(Long id, Double audioStart, Double audioEnd, String text, String pathToFile, Long speakerId, Long sourceId, Long wrong, Long correct, Timestamp deleted) {
        super(TextAudio.TEXT_AUDIO);

        set(0, id);
        set(1, audioStart);
        set(2, audioEnd);
        set(3, text);
        set(4, pathToFile);
        set(5, speakerId);
        set(6, sourceId);
        set(7, wrong);
        set(8, correct);
        set(9, deleted);
    }
}
