/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.tables.records;


import ch.fhnw.labeling_tool.jooq.tables.UserGroup;

import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroupRecord extends UpdatableRecordImpl<UserGroupRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = -2030703351;

    public void setId(Long value) {
        set(0, value);
    }

    public Long getId() {
        return (Long) get(0);
    }

    public void setName(String value) {
        set(1, value);
    }

    @Size(max = 100)
    public String getName() {
        return (String) get(1);
    }

    public void setDescription(String value) {
        set(2, value);
    }

    @Size(max = 16777215)
    public String getDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserGroup.USER_GROUP.ID;
    }

    @Override
    public Field<String> field2() {
        return UserGroup.USER_GROUP.NAME;
    }

    @Override
    public Field<String> field3() {
        return UserGroup.USER_GROUP.DESCRIPTION;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public UserGroupRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserGroupRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserGroupRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public UserGroupRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public UserGroupRecord() {
        super(UserGroup.USER_GROUP);
    }

    public UserGroupRecord(Long id, String name, String description) {
        super(UserGroup.USER_GROUP);

        set(0, id);
        set(1, name);
        set(2, description);
    }
}
