/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.tables.records;


import ch.fhnw.labeling_tool.jooq.enums.UserGroupRoleRole;
import ch.fhnw.labeling_tool.jooq.tables.UserGroupRole;

import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroupRoleRecord extends TableRecordImpl<UserGroupRoleRecord> implements Record3<UserGroupRoleRole, Long, Long> {

    private static final long serialVersionUID = 1514617219;

    public void setRole(UserGroupRoleRole value) {
        set(0, value);
    }

    public UserGroupRoleRole getRole() {
        return (UserGroupRoleRole) get(0);
    }

    public void setUserId(Long value) {
        set(1, value);
    }

    @NotNull
    public Long getUserId() {
        return (Long) get(1);
    }

    public void setUserGroupId(Long value) {
        set(2, value);
    }

    @NotNull
    public Long getUserGroupId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UserGroupRoleRole, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UserGroupRoleRole, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UserGroupRoleRole> field1() {
        return UserGroupRole.USER_GROUP_ROLE.ROLE;
    }

    @Override
    public Field<Long> field2() {
        return UserGroupRole.USER_GROUP_ROLE.USER_ID;
    }

    @Override
    public Field<Long> field3() {
        return UserGroupRole.USER_GROUP_ROLE.USER_GROUP_ID;
    }

    @Override
    public UserGroupRoleRole component1() {
        return getRole();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public Long component3() {
        return getUserGroupId();
    }

    @Override
    public UserGroupRoleRole value1() {
        return getRole();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public Long value3() {
        return getUserGroupId();
    }

    @Override
    public UserGroupRoleRecord value1(UserGroupRoleRole value) {
        setRole(value);
        return this;
    }

    @Override
    public UserGroupRoleRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserGroupRoleRecord value3(Long value) {
        setUserGroupId(value);
        return this;
    }

    @Override
    public UserGroupRoleRecord values(UserGroupRoleRole value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public UserGroupRoleRecord() {
        super(UserGroupRole.USER_GROUP_ROLE);
    }

    public UserGroupRoleRecord(UserGroupRoleRole role, Long userId, Long userGroupId) {
        super(UserGroupRole.USER_GROUP_ROLE);

        set(0, role);
        set(1, userId);
        set(2, userGroupId);
    }
}
