/*
 * This file is generated by jOOQ.
 */
package jooq.db


import jooq.db.tables.Audio
import jooq.db.tables.FlywaySchemaHistory
import jooq.db.tables.Textaudioindex
import jooq.db.tables.Transcript
import jooq.db.tables.User
import jooq.db.tables.Userandtextaudioindex

import org.jooq.Index
import org.jooq.OrderField
import org.jooq.impl.Internal


object Indexes {

  // -------------------------------------------------------------------------
  // INDEX definitions
  // -------------------------------------------------------------------------

  val AUDIO_PRIMARY = Indexes0.AUDIO_PRIMARY
  val FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX
  val FLYWAY_SCHEMA_HISTORY_PRIMARY = Indexes0.FLYWAY_SCHEMA_HISTORY_PRIMARY
  val TEXTAUDIOINDEX_PRIMARY = Indexes0.TEXTAUDIOINDEX_PRIMARY
  val TRANSCRIPT_PRIMARY = Indexes0.TRANSCRIPT_PRIMARY
  val USER_EMAIL = Indexes0.USER_EMAIL
  val USER_PRIMARY = Indexes0.USER_PRIMARY
  val USERANDTEXTAUDIOINDEX_PRIMARY = Indexes0.USERANDTEXTAUDIOINDEX_PRIMARY
  val USERANDTEXTAUDIOINDEX_UNI = Indexes0.USERANDTEXTAUDIOINDEX_UNI

  // -------------------------------------------------------------------------
  // [#1459] distribute members to avoid static initialisers > 64kb
  // -------------------------------------------------------------------------

  private object Indexes0 {
    val AUDIO_PRIMARY : Index = Internal.createIndex("PRIMARY", Audio.AUDIO, Array[OrderField [_] ](Audio.AUDIO.ID), true)
    val FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX : Index = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, Array[OrderField [_] ](FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS), false)
    val FLYWAY_SCHEMA_HISTORY_PRIMARY : Index = Internal.createIndex("PRIMARY", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, Array[OrderField [_] ](FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK), true)
    val TEXTAUDIOINDEX_PRIMARY : Index = Internal.createIndex("PRIMARY", Textaudioindex.TEXTAUDIOINDEX, Array[OrderField [_] ](Textaudioindex.TEXTAUDIOINDEX.ID), true)
    val TRANSCRIPT_PRIMARY : Index = Internal.createIndex("PRIMARY", Transcript.TRANSCRIPT, Array[OrderField [_] ](Transcript.TRANSCRIPT.ID), true)
    val USER_EMAIL : Index = Internal.createIndex("email", User.USER, Array[OrderField [_] ](User.USER.EMAIL), true)
    val USER_PRIMARY : Index = Internal.createIndex("PRIMARY", User.USER, Array[OrderField [_] ](User.USER.ID), true)
    val USERANDTEXTAUDIOINDEX_PRIMARY : Index = Internal.createIndex("PRIMARY", Userandtextaudioindex.USERANDTEXTAUDIOINDEX, Array[OrderField [_] ](Userandtextaudioindex.USERANDTEXTAUDIOINDEX.ID), true)
    val USERANDTEXTAUDIOINDEX_UNI : Index = Internal.createIndex("uni", Userandtextaudioindex.USERANDTEXTAUDIOINDEX, Array[OrderField [_] ](Userandtextaudioindex.USERANDTEXTAUDIOINDEX.USERID, Userandtextaudioindex.USERANDTEXTAUDIOINDEX.TEXTAUDIOINDEXID), true)
  }
}
