/*
 * This file is generated by jOOQ.
 */
package ch.labeling_tool.db.tables.daos


import ch.labeling_tool.db.tables.Avatar
import ch.labeling_tool.db.tables.records.AvatarRecord

import java.lang.Integer
import java.util.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl

import scala.Array
import scala.Byte


class AvatarDao(configuration : Configuration) extends DAOImpl[AvatarRecord, ch.labeling_tool.db.tables.pojos.Avatar, Integer](Avatar.AVATAR, classOf[ch.labeling_tool.db.tables.pojos.Avatar], configuration) {

  def this() = {
    this(null)
  }

  override protected def getId(o : ch.labeling_tool.db.tables.pojos.Avatar) : Integer = {
    o.getId
  }

  def fetchById(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.Avatar] = {
    fetch(Avatar.AVATAR.ID, values:_*)
  }

  def fetchOneById(value : Integer) : ch.labeling_tool.db.tables.pojos.Avatar = {
    fetchOne(Avatar.AVATAR.ID, value)
  }

  def fetchByUserid(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.Avatar] = {
    fetch(Avatar.AVATAR.USERID, values:_*)
  }

  def fetchOneByUserid(value : Integer) : ch.labeling_tool.db.tables.pojos.Avatar = {
    fetchOne(Avatar.AVATAR.USERID, value)
  }

  def fetchByAvatar(values : Array[Byte]*) : List[ch.labeling_tool.db.tables.pojos.Avatar] = {
    fetch(Avatar.AVATAR.AVATAR_, values:_*)
  }
}
