/*
 * This file is generated by jOOQ.
 */
package ch.labeling_tool.db.tables.daos


import ch.labeling_tool.db.tables.Chatmember
import ch.labeling_tool.db.tables.records.ChatmemberRecord

import java.lang.Integer
import java.util.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


class ChatmemberDao(configuration : Configuration) extends DAOImpl[ChatmemberRecord, ch.labeling_tool.db.tables.pojos.Chatmember, Integer](Chatmember.CHATMEMBER, classOf[ch.labeling_tool.db.tables.pojos.Chatmember], configuration) {

  def this() = {
    this(null)
  }

  override protected def getId(o : ch.labeling_tool.db.tables.pojos.Chatmember) : Integer = {
    o.getId
  }

  def fetchById(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.Chatmember] = {
    fetch(Chatmember.CHATMEMBER.ID, values:_*)
  }

  def fetchOneById(value : Integer) : ch.labeling_tool.db.tables.pojos.Chatmember = {
    fetchOne(Chatmember.CHATMEMBER.ID, value)
  }

  def fetchByChatid(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.Chatmember] = {
    fetch(Chatmember.CHATMEMBER.CHATID, values:_*)
  }

  def fetchByUserid(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.Chatmember] = {
    fetch(Chatmember.CHATMEMBER.USERID, values:_*)
  }
}
