/*
 * This file is generated by jOOQ.
 */
package ch.labeling_tool.db.tables.daos


import ch.labeling_tool.db.tables.Chat
import ch.labeling_tool.db.tables.records.ChatRecord

import java.lang.Integer
import java.lang.String
import java.util.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


class ChatDao(configuration : Configuration) extends DAOImpl[ChatRecord, ch.labeling_tool.db.tables.pojos.Chat, Integer](Chat.CHAT, classOf[ch.labeling_tool.db.tables.pojos.Chat], configuration) {

  def this() = {
    this(null)
  }

  override protected def getId(o : ch.labeling_tool.db.tables.pojos.Chat) : Integer = {
    o.getId
  }

  def fetchById(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.Chat] = {
    fetch(Chat.CHAT.ID, values:_*)
  }

  def fetchOneById(value : Integer) : ch.labeling_tool.db.tables.pojos.Chat = {
    fetchOne(Chat.CHAT.ID, value)
  }

  def fetchByChatname(values : String*) : List[ch.labeling_tool.db.tables.pojos.Chat] = {
    fetch(Chat.CHAT.CHATNAME, values:_*)
  }

  def fetchOneByChatname(value : String) : ch.labeling_tool.db.tables.pojos.Chat = {
    fetchOne(Chat.CHAT.CHATNAME, value)
  }
}
