/*
 * This file is generated by jOOQ.
 */
package ch.labeling_tool.db.tables.daos


import ch.labeling_tool.db.tables.Chatmessage
import ch.labeling_tool.db.tables.records.ChatmessageRecord

import java.lang.Integer
import java.lang.String
import java.util.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


class ChatmessageDao(configuration : Configuration) extends DAOImpl[ChatmessageRecord, ch.labeling_tool.db.tables.pojos.Chatmessage, Integer](Chatmessage.CHATMESSAGE, classOf[ch.labeling_tool.db.tables.pojos.Chatmessage], configuration) {

  def this() = {
    this(null)
  }

  override protected def getId(o : ch.labeling_tool.db.tables.pojos.Chatmessage) : Integer = {
    o.getId
  }

  def fetchById(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.Chatmessage] = {
    fetch(Chatmessage.CHATMESSAGE.ID, values:_*)
  }

  def fetchOneById(value : Integer) : ch.labeling_tool.db.tables.pojos.Chatmessage = {
    fetchOne(Chatmessage.CHATMESSAGE.ID, value)
  }

  def fetchByChatmemberid(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.Chatmessage] = {
    fetch(Chatmessage.CHATMESSAGE.CHATMEMBERID, values:_*)
  }

  def fetchByMessage(values : String*) : List[ch.labeling_tool.db.tables.pojos.Chatmessage] = {
    fetch(Chatmessage.CHATMESSAGE.MESSAGE, values:_*)
  }
}
