/*
 * This file is generated by jOOQ.
 */
package ch.labeling_tool.db.tables.daos


import ch.labeling_tool.db.tables.Textaudioindex
import ch.labeling_tool.db.tables.records.TextaudioindexRecord

import java.lang.Double
import java.lang.Integer
import java.util.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


class TextaudioindexDao(configuration : Configuration) extends DAOImpl[TextaudioindexRecord, ch.labeling_tool.db.tables.pojos.Textaudioindex, Integer](Textaudioindex.TEXTAUDIOINDEX, classOf[ch.labeling_tool.db.tables.pojos.Textaudioindex], configuration) {

  def this() = {
    this(null)
  }

  override protected def getId(o : ch.labeling_tool.db.tables.pojos.Textaudioindex) : Integer = {
    o.getId
  }

  def fetchById(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.Textaudioindex] = {
    fetch(Textaudioindex.TEXTAUDIOINDEX.ID, values:_*)
  }

  def fetchOneById(value : Integer) : ch.labeling_tool.db.tables.pojos.Textaudioindex = {
    fetchOne(Textaudioindex.TEXTAUDIOINDEX.ID, value)
  }

  def fetchBySamplingrate(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.Textaudioindex] = {
    fetch(Textaudioindex.TEXTAUDIOINDEX.SAMPLINGRATE, values:_*)
  }

  def fetchByTextstartpos(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.Textaudioindex] = {
    fetch(Textaudioindex.TEXTAUDIOINDEX.TEXTSTARTPOS, values:_*)
  }

  def fetchByTextendpos(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.Textaudioindex] = {
    fetch(Textaudioindex.TEXTAUDIOINDEX.TEXTENDPOS, values:_*)
  }

  def fetchByAudiostartpos(values : Double*) : List[ch.labeling_tool.db.tables.pojos.Textaudioindex] = {
    fetch(Textaudioindex.TEXTAUDIOINDEX.AUDIOSTARTPOS, values:_*)
  }

  def fetchByAudioendpos(values : Double*) : List[ch.labeling_tool.db.tables.pojos.Textaudioindex] = {
    fetch(Textaudioindex.TEXTAUDIOINDEX.AUDIOENDPOS, values:_*)
  }

  def fetchBySpeakerkey(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.Textaudioindex] = {
    fetch(Textaudioindex.TEXTAUDIOINDEX.SPEAKERKEY, values:_*)
  }

  def fetchByLabeled(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.Textaudioindex] = {
    fetch(Textaudioindex.TEXTAUDIOINDEX.LABELED, values:_*)
  }

  def fetchByCorrect(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.Textaudioindex] = {
    fetch(Textaudioindex.TEXTAUDIOINDEX.CORRECT, values:_*)
  }

  def fetchByWrong(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.Textaudioindex] = {
    fetch(Textaudioindex.TEXTAUDIOINDEX.WRONG, values:_*)
  }

  def fetchByTranscriptFileId(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.Textaudioindex] = {
    fetch(Textaudioindex.TEXTAUDIOINDEX.TRANSCRIPT_FILE_ID, values:_*)
  }
}
