/*
 * This file is generated by jOOQ.
 */
package ch.labeling_tool.db.tables.daos


import ch.labeling_tool.db.tables.User
import ch.labeling_tool.db.tables.records.UserRecord

import java.lang.Integer
import java.lang.String
import java.util.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


class UserDao(configuration : Configuration) extends DAOImpl[UserRecord, ch.labeling_tool.db.tables.pojos.User, Integer](User.USER, classOf[ch.labeling_tool.db.tables.pojos.User], configuration) {

  def this() = {
    this(null)
  }

  override protected def getId(o : ch.labeling_tool.db.tables.pojos.User) : Integer = {
    o.getId
  }

  def fetchById(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.User] = {
    fetch(User.USER.ID, values:_*)
  }

  def fetchOneById(value : Integer) : ch.labeling_tool.db.tables.pojos.User = {
    fetchOne(User.USER.ID, value)
  }

  def fetchByFirstname(values : String*) : List[ch.labeling_tool.db.tables.pojos.User] = {
    fetch(User.USER.FIRSTNAME, values:_*)
  }

  def fetchByLastname(values : String*) : List[ch.labeling_tool.db.tables.pojos.User] = {
    fetch(User.USER.LASTNAME, values:_*)
  }

  def fetchByEmail(values : String*) : List[ch.labeling_tool.db.tables.pojos.User] = {
    fetch(User.USER.EMAIL, values:_*)
  }

  def fetchOneByEmail(value : String) : ch.labeling_tool.db.tables.pojos.User = {
    fetchOne(User.USER.EMAIL, value)
  }

  def fetchByUsername(values : String*) : List[ch.labeling_tool.db.tables.pojos.User] = {
    fetch(User.USER.USERNAME, values:_*)
  }

  def fetchByAvatarversion(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.User] = {
    fetch(User.USER.AVATARVERSION, values:_*)
  }

  def fetchByPassword(values : String*) : List[ch.labeling_tool.db.tables.pojos.User] = {
    fetch(User.USER.PASSWORD, values:_*)
  }
}
