/*
 * This file is generated by jOOQ.
 */
package ch.labeling_tool.db.tables.daos


import ch.labeling_tool.db.tables.Userandtextaudioindex
import ch.labeling_tool.db.tables.records.UserandtextaudioindexRecord

import java.lang.Integer
import java.util.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


class UserandtextaudioindexDao(configuration : Configuration) extends DAOImpl[UserandtextaudioindexRecord, ch.labeling_tool.db.tables.pojos.Userandtextaudioindex, Integer](Userandtextaudioindex.USERANDTEXTAUDIOINDEX, classOf[ch.labeling_tool.db.tables.pojos.Userandtextaudioindex], configuration) {

  def this() = {
    this(null)
  }

  override protected def getId(o : ch.labeling_tool.db.tables.pojos.Userandtextaudioindex) : Integer = {
    o.getId
  }

  def fetchById(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.Userandtextaudioindex] = {
    fetch(Userandtextaudioindex.USERANDTEXTAUDIOINDEX.ID, values:_*)
  }

  def fetchOneById(value : Integer) : ch.labeling_tool.db.tables.pojos.Userandtextaudioindex = {
    fetchOne(Userandtextaudioindex.USERANDTEXTAUDIOINDEX.ID, value)
  }

  def fetchByUserid(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.Userandtextaudioindex] = {
    fetch(Userandtextaudioindex.USERANDTEXTAUDIOINDEX.USERID, values:_*)
  }

  def fetchByTextaudioindexid(values : Integer*) : List[ch.labeling_tool.db.tables.pojos.Userandtextaudioindex] = {
    fetch(Userandtextaudioindex.USERANDTEXTAUDIOINDEX.TEXTAUDIOINDEXID, values:_*)
  }
}
