/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = -1937748610;

    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    public final LabelingTool LABELING_TOOL = ch.fhnw.labeling_tool.jooq.LabelingTool.LABELING_TOOL;

    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        List result = new ArrayList();
        result.addAll(getSchemas0());
        return result;
    }

    private final List<Schema> getSchemas0() {
        return Arrays.<Schema>asList(
            LabelingTool.LABELING_TOOL);
    }
}
