/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq;


import ch.fhnw.labeling_tool.jooq.tables.CheckedRecording;
import ch.fhnw.labeling_tool.jooq.tables.CheckedTextAudio;
import ch.fhnw.labeling_tool.jooq.tables.Domain;
import ch.fhnw.labeling_tool.jooq.tables.Excerpt;
import ch.fhnw.labeling_tool.jooq.tables.FlywaySchemaHistory;
import ch.fhnw.labeling_tool.jooq.tables.OriginalText;
import ch.fhnw.labeling_tool.jooq.tables.Recording;
import ch.fhnw.labeling_tool.jooq.tables.Source;
import ch.fhnw.labeling_tool.jooq.tables.Speaker;
import ch.fhnw.labeling_tool.jooq.tables.TextAudio;
import ch.fhnw.labeling_tool.jooq.tables.User;
import ch.fhnw.labeling_tool.jooq.tables.UserGroup;
import ch.fhnw.labeling_tool.jooq.tables.UserGroupRole;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    public static final CheckedRecording CHECKED_RECORDING = CheckedRecording.CHECKED_RECORDING;

    public static final CheckedTextAudio CHECKED_TEXT_AUDIO = CheckedTextAudio.CHECKED_TEXT_AUDIO;

    public static final Domain DOMAIN = Domain.DOMAIN;

    public static final Excerpt EXCERPT = Excerpt.EXCERPT;

    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    public static final OriginalText ORIGINAL_TEXT = OriginalText.ORIGINAL_TEXT;

    public static final Recording RECORDING = Recording.RECORDING;

    public static final Source SOURCE = Source.SOURCE;

    public static final Speaker SPEAKER = Speaker.SPEAKER;

    public static final TextAudio TEXT_AUDIO = TextAudio.TEXT_AUDIO;

    public static final User USER = User.USER;

    public static final UserGroup USER_GROUP = UserGroup.USER_GROUP;

    public static final UserGroupRole USER_GROUP_ROLE = UserGroupRole.USER_GROUP_ROLE;
}
