/*
 * This file is generated by jOOQ.
 */
package ch.labeling_tool.db



object Tables {

  val AUDIO = ch.labeling_tool.db.tables.Audio.AUDIO

  val AVATAR = ch.labeling_tool.db.tables.Avatar.AVATAR

  val CHAT = ch.labeling_tool.db.tables.Chat.CHAT

  val CHATMEMBER = ch.labeling_tool.db.tables.Chatmember.CHATMEMBER

  val CHATMESSAGE = ch.labeling_tool.db.tables.Chatmessage.CHATMESSAGE

  val FLYWAY_SCHEMA_HISTORY = ch.labeling_tool.db.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

  val TEXTAUDIOINDEX = ch.labeling_tool.db.tables.Textaudioindex.TEXTAUDIOINDEX

  val TRANSCRIPT = ch.labeling_tool.db.tables.Transcript.TRANSCRIPT

  val USER = ch.labeling_tool.db.tables.User.USER

  val USERANDTEXTAUDIOINDEX = ch.labeling_tool.db.tables.Userandtextaudioindex.USERANDTEXTAUDIOINDEX
}
