/*
 * This file is generated by jOOQ.
 */
package ch.labeling_tool.db.tables.pojos


import java.io.Serializable
import java.lang.Integer
import java.lang.String
import java.lang.StringBuilder


case class Audio(
    id : Integer
  , path : String
  , fileid : Integer
) extends Serializable {

  def this (value : Audio) = {
    this(
        value.id
      , value.path
      , value.fileid
    )
  }

  def getId : Integer = {
    this.id
  }

  def getPath : String = {
    this.path
  }

  def getFileid : Integer = {
    this.fileid
  }

  override def toString : String = {
    val sb = new StringBuilder("Audio (")

    sb.append(id)
    sb.append(", ").append(path)
    sb.append(", ").append(fileid)

    sb.append(")")
    return sb.toString
  }
}
