/*
 * This file is generated by jOOQ.
 */
package ch.labeling_tool.db.tables.pojos


import java.io.Serializable
import java.lang.Integer
import java.lang.String
import java.lang.StringBuilder


case class Chatmessage(
    id : Integer
  , chatmemberid : Integer
  , message : String
) extends Serializable {

  def this (value : Chatmessage) = {
    this(
        value.id
      , value.chatmemberid
      , value.message
    )
  }

  def getId : Integer = {
    this.id
  }

  def getChatmemberid : Integer = {
    this.chatmemberid
  }

  def getMessage : String = {
    this.message
  }

  override def toString : String = {
    val sb = new StringBuilder("Chatmessage (")

    sb.append(id)
    sb.append(", ").append(chatmemberid)
    sb.append(", ").append(message)

    sb.append(")")
    return sb.toString
  }
}
