/*
 * This file is generated by jOOQ.
 */
package ch.labeling_tool.db.tables.pojos


import java.io.Serializable
import java.lang.Integer
import java.lang.String
import java.lang.StringBuilder


case class Chat(
    id : Integer
  , chatname : String
) extends Serializable {

  def this (value : Chat) = {
    this(
        value.id
      , value.chatname
    )
  }

  def getId : Integer = {
    this.id
  }

  def getChatname : String = {
    this.chatname
  }

  override def toString : String = {
    val sb = new StringBuilder("Chat (")

    sb.append(id)
    sb.append(", ").append(chatname)

    sb.append(")")
    return sb.toString
  }
}
